// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	config "github.com/JailtonJunior94/ai-spec-harness/internal/config"
	mock "github.com/stretchr/testify/mock"
)

// Resolver is an autogenerated mock type for the Resolver type
type Resolver struct {
	mock.Mock
}

type Resolver_Expecter struct {
	mock *mock.Mock
}

func (_m *Resolver) EXPECT() *Resolver_Expecter {
	return &Resolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function with given fields: cwd, overrides
func (_m *Resolver) Resolve(cwd string, overrides config.Runtime) (config.Runtime, error) {
	ret := _m.Called(cwd, overrides)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 config.Runtime
	var r1 error
	if rf, ok := ret.Get(0).(func(string, config.Runtime) (config.Runtime, error)); ok {
		return rf(cwd, overrides)
	}
	if rf, ok := ret.Get(0).(func(string, config.Runtime) config.Runtime); ok {
		r0 = rf(cwd, overrides)
	} else {
		r0 = ret.Get(0).(config.Runtime)
	}

	if rf, ok := ret.Get(1).(func(string, config.Runtime) error); ok {
		r1 = rf(cwd, overrides)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Resolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type Resolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - cwd string
//   - overrides config.Runtime
func (_e *Resolver_Expecter) Resolve(cwd any, overrides any) *Resolver_Resolve_Call {
	return &Resolver_Resolve_Call{Call: _e.mock.On("Resolve", cwd, overrides)}
}

func (_c *Resolver_Resolve_Call) Run(run func(cwd string, overrides config.Runtime)) *Resolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(config.Runtime))
	})
	return _c
}

func (_c *Resolver_Resolve_Call) Return(_a0 config.Runtime, _a1 error) *Resolver_Resolve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Resolver_Resolve_Call) RunAndReturn(run func(string, config.Runtime) (config.Runtime, error)) *Resolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// NewResolver creates a new instance of Resolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *Resolver {
	mock := &Resolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
