// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewSourceProvider creates a new instance of SourceProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSourceProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *SourceProvider {
	mock := &SourceProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SourceProvider is an autogenerated mock type for the SourceProvider type
type SourceProvider struct {
	mock.Mock
}

type SourceProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *SourceProvider) EXPECT() *SourceProvider_Expecter {
	return &SourceProvider_Expecter{mock: &_m.Mock}
}

// SourceDir provides a mock function for the type SourceProvider
func (_mock *SourceProvider) SourceDir() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SourceDir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// SourceProvider_SourceDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SourceDir'
type SourceProvider_SourceDir_Call struct {
	*mock.Call
}

// SourceDir is a helper method to define mock.On call
func (_e *SourceProvider_Expecter) SourceDir() *SourceProvider_SourceDir_Call {
	return &SourceProvider_SourceDir_Call{Call: _e.mock.On("SourceDir")}
}

func (_c *SourceProvider_SourceDir_Call) Run(run func()) *SourceProvider_SourceDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *SourceProvider_SourceDir_Call) Return(s string) *SourceProvider_SourceDir_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *SourceProvider_SourceDir_Call) RunAndReturn(run func() string) *SourceProvider_SourceDir_Call {
	_c.Call.Return(run)
	return _c
}
