// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LookPather is an autogenerated mock type for the LookPather type
type LookPather struct {
	mock.Mock
}

type LookPather_Expecter struct {
	mock *mock.Mock
}

func (_m *LookPather) EXPECT() *LookPather_Expecter {
	return &LookPather_Expecter{mock: &_m.Mock}
}

// LookPath provides a mock function with given fields: name
func (_m *LookPather) LookPath(name string) (string, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for LookPath")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LookPather_LookPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookPath'
type LookPather_LookPath_Call struct {
	*mock.Call
}

// LookPath is a helper method to define mock.On call
//   - name string
func (_e *LookPather_Expecter) LookPath(name any) *LookPather_LookPath_Call {
	return &LookPather_LookPath_Call{Call: _e.mock.On("LookPath", name)}
}

func (_c *LookPather_LookPath_Call) Run(run func(name string)) *LookPather_LookPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *LookPather_LookPath_Call) Return(_a0 string, _a1 error) *LookPather_LookPath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LookPather_LookPath_Call) RunAndReturn(run func(string) (string, error)) *LookPather_LookPath_Call {
	_c.Call.Return(run)
	return _c
}

// NewLookPather creates a new instance of LookPather. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLookPather(t interface {
	mock.TestingT
	Cleanup(func())
}) *LookPather {
	mock := &LookPather{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
