// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/JailtonJunior94/ai-spec-harness/internal/runtime/memory/durable"
	mock "github.com/stretchr/testify/mock"
)

// NewMemoryPort creates a new instance of MemoryPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMemoryPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MemoryPort {
	mock := &MemoryPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MemoryPort is an autogenerated mock type for the MemoryPort type
type MemoryPort struct {
	mock.Mock
}

type MemoryPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MemoryPort) EXPECT() *MemoryPort_Expecter {
	return &MemoryPort_Expecter{mock: &_m.Mock}
}

// BuildContext provides a mock function for the type MemoryPort
func (_mock *MemoryPort) BuildContext(ctx context.Context, scope durable.MemoryScope) (durable.MemoryContext, error) {
	ret := _mock.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for BuildContext")
	}

	var r0 durable.MemoryContext
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, durable.MemoryScope) (durable.MemoryContext, error)); ok {
		return returnFunc(ctx, scope)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, durable.MemoryScope) durable.MemoryContext); ok {
		r0 = returnFunc(ctx, scope)
	} else {
		r0 = ret.Get(0).(durable.MemoryContext)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, durable.MemoryScope) error); ok {
		r1 = returnFunc(ctx, scope)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MemoryPort_BuildContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildContext'
type MemoryPort_BuildContext_Call struct {
	*mock.Call
}

// BuildContext is a helper method to define mock.On call
//   - ctx context.Context
//   - scope durable.MemoryScope
func (_e *MemoryPort_Expecter) BuildContext(ctx any, scope any) *MemoryPort_BuildContext_Call {
	return &MemoryPort_BuildContext_Call{Call: _e.mock.On("BuildContext", ctx, scope)}
}

func (_c *MemoryPort_BuildContext_Call) Run(run func(ctx context.Context, scope durable.MemoryScope)) *MemoryPort_BuildContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 durable.MemoryScope
		if args[1] != nil {
			arg1 = args[1].(durable.MemoryScope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MemoryPort_BuildContext_Call) Return(memoryContext durable.MemoryContext, err error) *MemoryPort_BuildContext_Call {
	_c.Call.Return(memoryContext, err)
	return _c
}

func (_c *MemoryPort_BuildContext_Call) RunAndReturn(run func(ctx context.Context, scope durable.MemoryScope) (durable.MemoryContext, error)) *MemoryPort_BuildContext_Call {
	_c.Call.Return(run)
	return _c
}

// RecordSession provides a mock function for the type MemoryPort
func (_mock *MemoryPort) RecordSession(ctx context.Context, in durable.SessionFacts) (durable.MemoryReport, error) {
	ret := _mock.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for RecordSession")
	}

	var r0 durable.MemoryReport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, durable.SessionFacts) (durable.MemoryReport, error)); ok {
		return returnFunc(ctx, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, durable.SessionFacts) durable.MemoryReport); ok {
		r0 = returnFunc(ctx, in)
	} else {
		r0 = ret.Get(0).(durable.MemoryReport)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, durable.SessionFacts) error); ok {
		r1 = returnFunc(ctx, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MemoryPort_RecordSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordSession'
type MemoryPort_RecordSession_Call struct {
	*mock.Call
}

// RecordSession is a helper method to define mock.On call
//   - ctx context.Context
//   - in durable.SessionFacts
func (_e *MemoryPort_Expecter) RecordSession(ctx any, in any) *MemoryPort_RecordSession_Call {
	return &MemoryPort_RecordSession_Call{Call: _e.mock.On("RecordSession", ctx, in)}
}

func (_c *MemoryPort_RecordSession_Call) Run(run func(ctx context.Context, in durable.SessionFacts)) *MemoryPort_RecordSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 durable.SessionFacts
		if args[1] != nil {
			arg1 = args[1].(durable.SessionFacts)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MemoryPort_RecordSession_Call) Return(memoryReport durable.MemoryReport, err error) *MemoryPort_RecordSession_Call {
	_c.Call.Return(memoryReport, err)
	return _c
}

func (_c *MemoryPort_RecordSession_Call) RunAndReturn(run func(ctx context.Context, in durable.SessionFacts) (durable.MemoryReport, error)) *MemoryPort_RecordSession_Call {
	_c.Call.Return(run)
	return _c
}
