// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/JailtonJunior94/ai-spec-harness/internal/runtime"
	mock "github.com/stretchr/testify/mock"
)

// NewPersistenceFactory creates a new instance of PersistenceFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPersistenceFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *PersistenceFactory {
	mock := &PersistenceFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PersistenceFactory is an autogenerated mock type for the PersistenceFactory type
type PersistenceFactory struct {
	mock.Mock
}

type PersistenceFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *PersistenceFactory) EXPECT() *PersistenceFactory_Expecter {
	return &PersistenceFactory_Expecter{mock: &_m.Mock}
}

// New provides a mock function for the type PersistenceFactory
func (_mock *PersistenceFactory) New(evidenceDir string) (runtime.Persistence, error) {
	ret := _mock.Called(evidenceDir)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 runtime.Persistence
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (runtime.Persistence, error)); ok {
		return returnFunc(evidenceDir)
	}
	if returnFunc, ok := ret.Get(0).(func(string) runtime.Persistence); ok {
		r0 = returnFunc(evidenceDir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(runtime.Persistence)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(evidenceDir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// PersistenceFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type PersistenceFactory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - evidenceDir string
func (_e *PersistenceFactory_Expecter) New(evidenceDir any) *PersistenceFactory_New_Call {
	return &PersistenceFactory_New_Call{Call: _e.mock.On("New", evidenceDir)}
}

func (_c *PersistenceFactory_New_Call) Run(run func(evidenceDir string)) *PersistenceFactory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *PersistenceFactory_New_Call) Return(persistence runtime.Persistence, err error) *PersistenceFactory_New_Call {
	_c.Call.Return(persistence, err)
	return _c
}

func (_c *PersistenceFactory_New_Call) RunAndReturn(run func(evidenceDir string) (runtime.Persistence, error)) *PersistenceFactory_New_Call {
	_c.Call.Return(run)
	return _c
}
