// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/JailtonJunior94/ai-spec-harness/internal/runtime"
	"github.com/JailtonJunior94/ai-spec-harness/internal/runtime/events"
	mock "github.com/stretchr/testify/mock"
)

// NewPersistence creates a new instance of Persistence. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPersistence(t interface {
	mock.TestingT
	Cleanup(func())
}) *Persistence {
	mock := &Persistence{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Persistence is an autogenerated mock type for the Persistence type
type Persistence struct {
	mock.Mock
}

type Persistence_Expecter struct {
	mock *mock.Mock
}

func (_m *Persistence) EXPECT() *Persistence_Expecter {
	return &Persistence_Expecter{mock: &_m.Mock}
}

// AppendEvent provides a mock function for the type Persistence
func (_mock *Persistence) AppendEvent(evt events.Event) error {
	ret := _mock.Called(evt)

	if len(ret) == 0 {
		panic("no return value specified for AppendEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(events.Event) error); ok {
		r0 = returnFunc(evt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Persistence_AppendEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendEvent'
type Persistence_AppendEvent_Call struct {
	*mock.Call
}

// AppendEvent is a helper method to define mock.On call
//   - evt events.Event
func (_e *Persistence_Expecter) AppendEvent(evt any) *Persistence_AppendEvent_Call {
	return &Persistence_AppendEvent_Call{Call: _e.mock.On("AppendEvent", evt)}
}

func (_c *Persistence_AppendEvent_Call) Run(run func(evt events.Event)) *Persistence_AppendEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 events.Event
		if args[0] != nil {
			arg0 = args[0].(events.Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Persistence_AppendEvent_Call) Return(err error) *Persistence_AppendEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Persistence_AppendEvent_Call) RunAndReturn(run func(evt events.Event) error) *Persistence_AppendEvent_Call {
	_c.Call.Return(run)
	return _c
}

// EnrichReport provides a mock function for the type Persistence
func (_mock *Persistence) EnrichReport(summary runtime.Summary) error {
	ret := _mock.Called(summary)

	if len(ret) == 0 {
		panic("no return value specified for EnrichReport")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(runtime.Summary) error); ok {
		r0 = returnFunc(summary)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Persistence_EnrichReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnrichReport'
type Persistence_EnrichReport_Call struct {
	*mock.Call
}

// EnrichReport is a helper method to define mock.On call
//   - summary runtime.Summary
func (_e *Persistence_Expecter) EnrichReport(summary any) *Persistence_EnrichReport_Call {
	return &Persistence_EnrichReport_Call{Call: _e.mock.On("EnrichReport", summary)}
}

func (_c *Persistence_EnrichReport_Call) Run(run func(summary runtime.Summary)) *Persistence_EnrichReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 runtime.Summary
		if args[0] != nil {
			arg0 = args[0].(runtime.Summary)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Persistence_EnrichReport_Call) Return(err error) *Persistence_EnrichReport_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Persistence_EnrichReport_Call) RunAndReturn(run func(summary runtime.Summary) error) *Persistence_EnrichReport_Call {
	_c.Call.Return(run)
	return _c
}

// WriteToolCalls provides a mock function for the type Persistence
func (_mock *Persistence) WriteToolCalls(summary []events.ToolCallSummary) error {
	ret := _mock.Called(summary)

	if len(ret) == 0 {
		panic("no return value specified for WriteToolCalls")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]events.ToolCallSummary) error); ok {
		r0 = returnFunc(summary)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Persistence_WriteToolCalls_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteToolCalls'
type Persistence_WriteToolCalls_Call struct {
	*mock.Call
}

// WriteToolCalls is a helper method to define mock.On call
//   - summary []events.ToolCallSummary
func (_e *Persistence_Expecter) WriteToolCalls(summary any) *Persistence_WriteToolCalls_Call {
	return &Persistence_WriteToolCalls_Call{Call: _e.mock.On("WriteToolCalls", summary)}
}

func (_c *Persistence_WriteToolCalls_Call) Run(run func(summary []events.ToolCallSummary)) *Persistence_WriteToolCalls_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []events.ToolCallSummary
		if args[0] != nil {
			arg0 = args[0].([]events.ToolCallSummary)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Persistence_WriteToolCalls_Call) Return(err error) *Persistence_WriteToolCalls_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Persistence_WriteToolCalls_Call) RunAndReturn(run func(summary []events.ToolCallSummary) error) *Persistence_WriteToolCalls_Call {
	_c.Call.Return(run)
	return _c
}
