// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	specs "github.com/JailtonJunior94/ai-spec-harness/internal/runtime/specs"
)

// Prober is an autogenerated mock type for the Prober type
type Prober struct {
	mock.Mock
}

type Prober_Expecter struct {
	mock *mock.Mock
}

func (_m *Prober) EXPECT() *Prober_Expecter {
	return &Prober_Expecter{mock: &_m.Mock}
}

// EnsureAvailable provides a mock function with given fields: ctx, spec
func (_m *Prober) EnsureAvailable(ctx context.Context, spec specs.Spec) (specs.Launcher, error) {
	ret := _m.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for EnsureAvailable")
	}

	var r0 specs.Launcher
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, specs.Spec) (specs.Launcher, error)); ok {
		return rf(ctx, spec)
	}
	if rf, ok := ret.Get(0).(func(context.Context, specs.Spec) specs.Launcher); ok {
		r0 = rf(ctx, spec)
	} else {
		r0 = ret.Get(0).(specs.Launcher)
	}

	if rf, ok := ret.Get(1).(func(context.Context, specs.Spec) error); ok {
		r1 = rf(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Prober_EnsureAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureAvailable'
type Prober_EnsureAvailable_Call struct {
	*mock.Call
}

// EnsureAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - spec specs.Spec
func (_e *Prober_Expecter) EnsureAvailable(ctx any, spec any) *Prober_EnsureAvailable_Call {
	return &Prober_EnsureAvailable_Call{Call: _e.mock.On("EnsureAvailable", ctx, spec)}
}

func (_c *Prober_EnsureAvailable_Call) Run(run func(ctx context.Context, spec specs.Spec)) *Prober_EnsureAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(specs.Spec))
	})
	return _c
}

func (_c *Prober_EnsureAvailable_Call) Return(_a0 specs.Launcher, _a1 error) *Prober_EnsureAvailable_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Prober_EnsureAvailable_Call) RunAndReturn(run func(context.Context, specs.Spec) (specs.Launcher, error)) *Prober_EnsureAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// NewProber creates a new instance of Prober. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProber(t interface {
	mock.TestingT
	Cleanup(func())
}) *Prober {
	mock := &Prober{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
