// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/JailtonJunior94/ai-spec-harness/internal/runtime/specs"
	mock "github.com/stretchr/testify/mock"
)

// NewProber creates a new instance of Prober. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProber(t interface {
	mock.TestingT
	Cleanup(func())
}) *Prober {
	mock := &Prober{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Prober is an autogenerated mock type for the Prober type
type Prober struct {
	mock.Mock
}

type Prober_Expecter struct {
	mock *mock.Mock
}

func (_m *Prober) EXPECT() *Prober_Expecter {
	return &Prober_Expecter{mock: &_m.Mock}
}

// EnsureAvailable provides a mock function for the type Prober
func (_mock *Prober) EnsureAvailable(ctx context.Context, spec specs.Spec) (specs.Launcher, error) {
	ret := _mock.Called(ctx, spec)

	if len(ret) == 0 {
		panic("no return value specified for EnsureAvailable")
	}

	var r0 specs.Launcher
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, specs.Spec) (specs.Launcher, error)); ok {
		return returnFunc(ctx, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, specs.Spec) specs.Launcher); ok {
		r0 = returnFunc(ctx, spec)
	} else {
		r0 = ret.Get(0).(specs.Launcher)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, specs.Spec) error); ok {
		r1 = returnFunc(ctx, spec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Prober_EnsureAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureAvailable'
type Prober_EnsureAvailable_Call struct {
	*mock.Call
}

// EnsureAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - spec specs.Spec
func (_e *Prober_Expecter) EnsureAvailable(ctx any, spec any) *Prober_EnsureAvailable_Call {
	return &Prober_EnsureAvailable_Call{Call: _e.mock.On("EnsureAvailable", ctx, spec)}
}

func (_c *Prober_EnsureAvailable_Call) Run(run func(ctx context.Context, spec specs.Spec)) *Prober_EnsureAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 specs.Spec
		if args[1] != nil {
			arg1 = args[1].(specs.Spec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Prober_EnsureAvailable_Call) Return(launcher specs.Launcher, err error) *Prober_EnsureAvailable_Call {
	_c.Call.Return(launcher, err)
	return _c
}

func (_c *Prober_EnsureAvailable_Call) RunAndReturn(run func(ctx context.Context, spec specs.Spec) (specs.Launcher, error)) *Prober_EnsureAvailable_Call {
	_c.Call.Return(run)
	return _c
}
