// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/JailtonJunior94/ai-spec-harness/internal/runtime/events"
	mock "github.com/stretchr/testify/mock"
)

// NewRenderer creates a new instance of Renderer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRenderer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Renderer {
	mock := &Renderer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Renderer is an autogenerated mock type for the Renderer type
type Renderer struct {
	mock.Mock
}

type Renderer_Expecter struct {
	mock *mock.Mock
}

func (_m *Renderer) EXPECT() *Renderer_Expecter {
	return &Renderer_Expecter{mock: &_m.Mock}
}

// Render provides a mock function for the type Renderer
func (_mock *Renderer) Render(evt events.Event) {
	_mock.Called(evt)
	return
}

// Renderer_Render_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Render'
type Renderer_Render_Call struct {
	*mock.Call
}

// Render is a helper method to define mock.On call
//   - evt events.Event
func (_e *Renderer_Expecter) Render(evt any) *Renderer_Render_Call {
	return &Renderer_Render_Call{Call: _e.mock.On("Render", evt)}
}

func (_c *Renderer_Render_Call) Run(run func(evt events.Event)) *Renderer_Render_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 events.Event
		if args[0] != nil {
			arg0 = args[0].(events.Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Renderer_Render_Call) Return() *Renderer_Render_Call {
	_c.Call.Return()
	return _c
}

func (_c *Renderer_Render_Call) RunAndReturn(run func(evt events.Event)) *Renderer_Render_Call {
	_c.Run(run)
	return _c
}
