// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RetryClassifier is an autogenerated mock type for the RetryClassifier type
type RetryClassifier struct {
	mock.Mock
}

type RetryClassifier_Expecter struct {
	mock *mock.Mock
}

func (_m *RetryClassifier) EXPECT() *RetryClassifier_Expecter {
	return &RetryClassifier_Expecter{mock: &_m.Mock}
}

// IsTransient provides a mock function with given fields: err
func (_m *RetryClassifier) IsTransient(err error) bool {
	ret := _m.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for IsTransient")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(error) bool); ok {
		r0 = rf(err)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// RetryClassifier_IsTransient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTransient'
type RetryClassifier_IsTransient_Call struct {
	*mock.Call
}

// IsTransient is a helper method to define mock.On call
//   - err error
func (_e *RetryClassifier_Expecter) IsTransient(err any) *RetryClassifier_IsTransient_Call {
	return &RetryClassifier_IsTransient_Call{Call: _e.mock.On("IsTransient", err)}
}

func (_c *RetryClassifier_IsTransient_Call) Run(run func(err error)) *RetryClassifier_IsTransient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(error))
	})
	return _c
}

func (_c *RetryClassifier_IsTransient_Call) Return(_a0 bool) *RetryClassifier_IsTransient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RetryClassifier_IsTransient_Call) RunAndReturn(run func(error) bool) *RetryClassifier_IsTransient_Call {
	_c.Call.Return(run)
	return _c
}

// NewRetryClassifier creates a new instance of RetryClassifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRetryClassifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *RetryClassifier {
	mock := &RetryClassifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
