// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/JailtonJunior94/ai-spec-harness/internal/hookpolicy"
	mock "github.com/stretchr/testify/mock"
)

// NewGitScope creates a new instance of GitScope. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGitScope(t interface {
	mock.TestingT
	Cleanup(func())
}) *GitScope {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &GitScope{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// GitScope is an autogenerated mock type for the GitScope type
type GitScope struct {
	mock.Mock
}

type GitScope_Expecter struct {
	mock *mock.Mock
}

func (_m *GitScope) EXPECT() *GitScope_Expecter {
	return &GitScope_Expecter{mock: &_m.Mock}
}

// Fingerprint provides a mock function for the type GitScope
func (_mock *GitScope) Fingerprint() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Fingerprint")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// GitScope_Fingerprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fingerprint'
type GitScope_Fingerprint_Call struct {
	*mock.Call
}

// Fingerprint is a helper method to define mock.On call
func (_e *GitScope_Expecter) Fingerprint() *GitScope_Fingerprint_Call {
	return &GitScope_Fingerprint_Call{Call: _e.mock.On("Fingerprint")}
}

func (_c *GitScope_Fingerprint_Call) Run(run func()) *GitScope_Fingerprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GitScope_Fingerprint_Call) Return(s string) *GitScope_Fingerprint_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *GitScope_Fingerprint_Call) RunAndReturn(run func() string) *GitScope_Fingerprint_Call {
	_c.Call.Return(run)
	return _c
}

// Operations provides a mock function for the type GitScope
func (_mock *GitScope) Operations() []hookpolicy.GitOperation {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Operations")
	}

	var r0 []hookpolicy.GitOperation
	if returnFunc, ok := ret.Get(0).(func() []hookpolicy.GitOperation); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]hookpolicy.GitOperation)
		}
	}
	return r0
}

// GitScope_Operations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Operations'
type GitScope_Operations_Call struct {
	*mock.Call
}

// Operations is a helper method to define mock.On call
func (_e *GitScope_Expecter) Operations() *GitScope_Operations_Call {
	return &GitScope_Operations_Call{Call: _e.mock.On("Operations")}
}

func (_c *GitScope_Operations_Call) Run(run func()) *GitScope_Operations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GitScope_Operations_Call) Return(gitOperations []hookpolicy.GitOperation) *GitScope_Operations_Call {
	_c.Call.Return(gitOperations)
	return _c
}

func (_c *GitScope_Operations_Call) RunAndReturn(run func() []hookpolicy.GitOperation) *GitScope_Operations_Call {
	_c.Call.Return(run)
	return _c
}
