// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/JailtonJunior94/ai-spec-harness/internal/runtime/hooks"
	mock "github.com/stretchr/testify/mock"
)

// NewDispatcher creates a new instance of Dispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Dispatcher {
	mock := &Dispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Dispatcher is an autogenerated mock type for the Dispatcher type
type Dispatcher struct {
	mock.Mock
}

type Dispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *Dispatcher) EXPECT() *Dispatcher_Expecter {
	return &Dispatcher_Expecter{mock: &_m.Mock}
}

// Dispatch provides a mock function for the type Dispatcher
func (_mock *Dispatcher) Dispatch(ctx context.Context, point string, evt hooks.Event) error {
	ret := _mock.Called(ctx, point, evt)

	if len(ret) == 0 {
		panic("no return value specified for Dispatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, hooks.Event) error); ok {
		r0 = returnFunc(ctx, point, evt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Dispatcher_Dispatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dispatch'
type Dispatcher_Dispatch_Call struct {
	*mock.Call
}

// Dispatch is a helper method to define mock.On call
//   - ctx context.Context
//   - point string
//   - evt hooks.Event
func (_e *Dispatcher_Expecter) Dispatch(ctx any, point any, evt any) *Dispatcher_Dispatch_Call {
	return &Dispatcher_Dispatch_Call{Call: _e.mock.On("Dispatch", ctx, point, evt)}
}

func (_c *Dispatcher_Dispatch_Call) Run(run func(ctx context.Context, point string, evt hooks.Event)) *Dispatcher_Dispatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 hooks.Event
		if args[2] != nil {
			arg2 = args[2].(hooks.Event)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Dispatcher_Dispatch_Call) Return(err error) *Dispatcher_Dispatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Dispatcher_Dispatch_Call) RunAndReturn(run func(ctx context.Context, point string, evt hooks.Event) error) *Dispatcher_Dispatch_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type Dispatcher
func (_mock *Dispatcher) Register(point string, hook hooks.Hook) {
	_mock.Called(point, hook)
	return
}

// Dispatcher_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type Dispatcher_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - point string
//   - hook hooks.Hook
func (_e *Dispatcher_Expecter) Register(point any, hook any) *Dispatcher_Register_Call {
	return &Dispatcher_Register_Call{Call: _e.mock.On("Register", point, hook)}
}

func (_c *Dispatcher_Register_Call) Run(run func(point string, hook hooks.Hook)) *Dispatcher_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 hooks.Hook
		if args[1] != nil {
			arg1 = args[1].(hooks.Hook)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Dispatcher_Register_Call) Return() *Dispatcher_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *Dispatcher_Register_Call) RunAndReturn(run func(point string, hook hooks.Hook)) *Dispatcher_Register_Call {
	_c.Run(run)
	return _c
}
