// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	hooks "github.com/JailtonJunior94/ai-spec-harness/internal/runtime/hooks"
	mock "github.com/stretchr/testify/mock"
)

// Hook is an autogenerated mock type for the Hook type
type Hook struct {
	mock.Mock
}

type Hook_Expecter struct {
	mock *mock.Mock
}

func (_m *Hook) EXPECT() *Hook_Expecter {
	return &Hook_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with no fields
func (_m *Hook) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Hook_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Hook_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Hook_Expecter) Name() *Hook_Name_Call {
	return &Hook_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *Hook_Name_Call) Run(run func()) *Hook_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Hook_Name_Call) Return(_a0 string) *Hook_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Hook_Name_Call) RunAndReturn(run func() string) *Hook_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function with given fields: ctx, evt
func (_m *Hook) Run(ctx context.Context, evt hooks.Event) error {
	ret := _m.Called(ctx, evt)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, hooks.Event) error); ok {
		r0 = rf(ctx, evt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Hook_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type Hook_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - evt hooks.Event
func (_e *Hook_Expecter) Run(ctx any, evt any) *Hook_Run_Call {
	return &Hook_Run_Call{Call: _e.mock.On("Run", ctx, evt)}
}

func (_c *Hook_Run_Call) Run(run func(ctx context.Context, evt hooks.Event)) *Hook_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(hooks.Event))
	})
	return _c
}

func (_c *Hook_Run_Call) Return(_a0 error) *Hook_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Hook_Run_Call) RunAndReturn(run func(context.Context, hooks.Event) error) *Hook_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewHook creates a new instance of Hook. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHook(t interface {
	mock.TestingT
	Cleanup(func())
}) *Hook {
	mock := &Hook{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
