// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/JailtonJunior94/ai-spec-harness/internal/approval"
	mock "github.com/stretchr/testify/mock"
)

// NewFixer creates a new instance of Fixer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFixer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Fixer {
	mock := &Fixer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Fixer is an autogenerated mock type for the Fixer type
type Fixer struct {
	mock.Mock
}

type Fixer_Expecter struct {
	mock *mock.Mock
}

func (_m *Fixer) EXPECT() *Fixer_Expecter {
	return &Fixer_Expecter{mock: &_m.Mock}
}

// Fix provides a mock function for the type Fixer
func (_mock *Fixer) Fix(ctx context.Context, request approval.FixRequest) error {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Fix")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, approval.FixRequest) error); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Fixer_Fix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fix'
type Fixer_Fix_Call struct {
	*mock.Call
}

// Fix is a helper method to define mock.On call
//   - ctx context.Context
//   - request approval.FixRequest
func (_e *Fixer_Expecter) Fix(ctx any, request any) *Fixer_Fix_Call {
	return &Fixer_Fix_Call{Call: _e.mock.On("Fix", ctx, request)}
}

func (_c *Fixer_Fix_Call) Run(run func(ctx context.Context, request approval.FixRequest)) *Fixer_Fix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 approval.FixRequest
		if args[1] != nil {
			arg1 = args[1].(approval.FixRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Fixer_Fix_Call) Return(err error) *Fixer_Fix_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Fixer_Fix_Call) RunAndReturn(run func(ctx context.Context, request approval.FixRequest) error) *Fixer_Fix_Call {
	_c.Call.Return(run)
	return _c
}
