// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/JailtonJunior94/ai-spec-harness/internal/approval"
	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Checkpoint provides a mock function for the type Repository
func (_mock *Repository) Checkpoint(ctx context.Context) (approval.Checkpoint, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Checkpoint")
	}

	var r0 approval.Checkpoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (approval.Checkpoint, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) approval.Checkpoint); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(approval.Checkpoint)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_Checkpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Checkpoint'
type Repository_Checkpoint_Call struct {
	*mock.Call
}

// Checkpoint is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Repository_Expecter) Checkpoint(ctx any) *Repository_Checkpoint_Call {
	return &Repository_Checkpoint_Call{Call: _e.mock.On("Checkpoint", ctx)}
}

func (_c *Repository_Checkpoint_Call) Run(run func(ctx context.Context)) *Repository_Checkpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Repository_Checkpoint_Call) Return(checkpoint approval.Checkpoint, err error) *Repository_Checkpoint_Call {
	_c.Call.Return(checkpoint, err)
	return _c
}

func (_c *Repository_Checkpoint_Call) RunAndReturn(run func(ctx context.Context) (approval.Checkpoint, error)) *Repository_Checkpoint_Call {
	_c.Call.Return(run)
	return _c
}

// Delta provides a mock function for the type Repository
func (_mock *Repository) Delta(ctx context.Context, since approval.Checkpoint) (approval.ReviewTarget, error) {
	ret := _mock.Called(ctx, since)

	if len(ret) == 0 {
		panic("no return value specified for Delta")
	}

	var r0 approval.ReviewTarget
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, approval.Checkpoint) (approval.ReviewTarget, error)); ok {
		return returnFunc(ctx, since)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, approval.Checkpoint) approval.ReviewTarget); ok {
		r0 = returnFunc(ctx, since)
	} else {
		r0 = ret.Get(0).(approval.ReviewTarget)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, approval.Checkpoint) error); ok {
		r1 = returnFunc(ctx, since)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_Delta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delta'
type Repository_Delta_Call struct {
	*mock.Call
}

// Delta is a helper method to define mock.On call
//   - ctx context.Context
//   - since approval.Checkpoint
func (_e *Repository_Expecter) Delta(ctx any, since any) *Repository_Delta_Call {
	return &Repository_Delta_Call{Call: _e.mock.On("Delta", ctx, since)}
}

func (_c *Repository_Delta_Call) Run(run func(ctx context.Context, since approval.Checkpoint)) *Repository_Delta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 approval.Checkpoint
		if args[1] != nil {
			arg1 = args[1].(approval.Checkpoint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Repository_Delta_Call) Return(reviewTarget approval.ReviewTarget, err error) *Repository_Delta_Call {
	_c.Call.Return(reviewTarget, err)
	return _c
}

func (_c *Repository_Delta_Call) RunAndReturn(run func(ctx context.Context, since approval.Checkpoint) (approval.ReviewTarget, error)) *Repository_Delta_Call {
	_c.Call.Return(run)
	return _c
}

// FullTarget provides a mock function for the type Repository
func (_mock *Repository) FullTarget(ctx context.Context) (approval.ReviewTarget, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FullTarget")
	}

	var r0 approval.ReviewTarget
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (approval.ReviewTarget, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) approval.ReviewTarget); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(approval.ReviewTarget)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_FullTarget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FullTarget'
type Repository_FullTarget_Call struct {
	*mock.Call
}

// FullTarget is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Repository_Expecter) FullTarget(ctx any) *Repository_FullTarget_Call {
	return &Repository_FullTarget_Call{Call: _e.mock.On("FullTarget", ctx)}
}

func (_c *Repository_FullTarget_Call) Run(run func(ctx context.Context)) *Repository_FullTarget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Repository_FullTarget_Call) Return(reviewTarget approval.ReviewTarget, err error) *Repository_FullTarget_Call {
	_c.Call.Return(reviewTarget, err)
	return _c
}

func (_c *Repository_FullTarget_Call) RunAndReturn(run func(ctx context.Context) (approval.ReviewTarget, error)) *Repository_FullTarget_Call {
	_c.Call.Return(run)
	return _c
}
