// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/JailtonJunior94/ai-spec-harness/internal/approval"
	mock "github.com/stretchr/testify/mock"
)

// NewReviewer creates a new instance of Reviewer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReviewer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Reviewer {
	mock := &Reviewer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Reviewer is an autogenerated mock type for the Reviewer type
type Reviewer struct {
	mock.Mock
}

type Reviewer_Expecter struct {
	mock *mock.Mock
}

func (_m *Reviewer) EXPECT() *Reviewer_Expecter {
	return &Reviewer_Expecter{mock: &_m.Mock}
}

// Review provides a mock function for the type Reviewer
func (_mock *Reviewer) Review(ctx context.Context, request approval.ReviewRequest) (approval.ReviewerOutput, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Review")
	}

	var r0 approval.ReviewerOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, approval.ReviewRequest) (approval.ReviewerOutput, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, approval.ReviewRequest) approval.ReviewerOutput); ok {
		r0 = returnFunc(ctx, request)
	} else {
		r0 = ret.Get(0).(approval.ReviewerOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, approval.ReviewRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Reviewer_Review_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Review'
type Reviewer_Review_Call struct {
	*mock.Call
}

// Review is a helper method to define mock.On call
//   - ctx context.Context
//   - request approval.ReviewRequest
func (_e *Reviewer_Expecter) Review(ctx any, request any) *Reviewer_Review_Call {
	return &Reviewer_Review_Call{Call: _e.mock.On("Review", ctx, request)}
}

func (_c *Reviewer_Review_Call) Run(run func(ctx context.Context, request approval.ReviewRequest)) *Reviewer_Review_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 approval.ReviewRequest
		if args[1] != nil {
			arg1 = args[1].(approval.ReviewRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Reviewer_Review_Call) Return(reviewerOutput approval.ReviewerOutput, err error) *Reviewer_Review_Call {
	_c.Call.Return(reviewerOutput, err)
	return _c
}

func (_c *Reviewer_Review_Call) RunAndReturn(run func(ctx context.Context, request approval.ReviewRequest) (approval.ReviewerOutput, error)) *Reviewer_Review_Call {
	_c.Call.Return(run)
	return _c
}
