// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	memory "github.com/JailtonJunior94/ai-spec-harness/internal/runtime/memory"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// ReadTask provides a mock function with given fields: ctx, taskFileName
func (_m *Store) ReadTask(ctx context.Context, taskFileName string) (memory.Document, error) {
	ret := _m.Called(ctx, taskFileName)

	if len(ret) == 0 {
		panic("no return value specified for ReadTask")
	}

	var r0 memory.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (memory.Document, error)); ok {
		return rf(ctx, taskFileName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) memory.Document); ok {
		r0 = rf(ctx, taskFileName)
	} else {
		r0 = ret.Get(0).(memory.Document)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, taskFileName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ReadTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadTask'
type Store_ReadTask_Call struct {
	*mock.Call
}

// ReadTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskFileName string
func (_e *Store_Expecter) ReadTask(ctx any, taskFileName any) *Store_ReadTask_Call {
	return &Store_ReadTask_Call{Call: _e.mock.On("ReadTask", ctx, taskFileName)}
}

func (_c *Store_ReadTask_Call) Run(run func(ctx context.Context, taskFileName string)) *Store_ReadTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_ReadTask_Call) Return(_a0 memory.Document, _a1 error) *Store_ReadTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ReadTask_Call) RunAndReturn(run func(context.Context, string) (memory.Document, error)) *Store_ReadTask_Call {
	_c.Call.Return(run)
	return _c
}

// ReadWorkflow provides a mock function with given fields: ctx
func (_m *Store) ReadWorkflow(ctx context.Context) (memory.Document, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReadWorkflow")
	}

	var r0 memory.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (memory.Document, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) memory.Document); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(memory.Document)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_ReadWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadWorkflow'
type Store_ReadWorkflow_Call struct {
	*mock.Call
}

// ReadWorkflow is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Store_Expecter) ReadWorkflow(ctx any) *Store_ReadWorkflow_Call {
	return &Store_ReadWorkflow_Call{Call: _e.mock.On("ReadWorkflow", ctx)}
}

func (_c *Store_ReadWorkflow_Call) Run(run func(ctx context.Context)) *Store_ReadWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Store_ReadWorkflow_Call) Return(_a0 memory.Document, _a1 error) *Store_ReadWorkflow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_ReadWorkflow_Call) RunAndReturn(run func(context.Context) (memory.Document, error)) *Store_ReadWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// WriteTask provides a mock function with given fields: ctx, taskFileName, content, mode
func (_m *Store) WriteTask(ctx context.Context, taskFileName string, content string, mode memory.WriteMode) error {
	ret := _m.Called(ctx, taskFileName, content, mode)

	if len(ret) == 0 {
		panic("no return value specified for WriteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, memory.WriteMode) error); ok {
		r0 = rf(ctx, taskFileName, content, mode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_WriteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteTask'
type Store_WriteTask_Call struct {
	*mock.Call
}

// WriteTask is a helper method to define mock.On call
//   - ctx context.Context
//   - taskFileName string
//   - content string
//   - mode memory.WriteMode
func (_e *Store_Expecter) WriteTask(ctx any, taskFileName any, content any, mode any) *Store_WriteTask_Call {
	return &Store_WriteTask_Call{Call: _e.mock.On("WriteTask", ctx, taskFileName, content, mode)}
}

func (_c *Store_WriteTask_Call) Run(run func(ctx context.Context, taskFileName string, content string, mode memory.WriteMode)) *Store_WriteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(memory.WriteMode))
	})
	return _c
}

func (_c *Store_WriteTask_Call) Return(_a0 error) *Store_WriteTask_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_WriteTask_Call) RunAndReturn(run func(context.Context, string, string, memory.WriteMode) error) *Store_WriteTask_Call {
	_c.Call.Return(run)
	return _c
}

// WriteWorkflow provides a mock function with given fields: ctx, content, mode
func (_m *Store) WriteWorkflow(ctx context.Context, content string, mode memory.WriteMode) error {
	ret := _m.Called(ctx, content, mode)

	if len(ret) == 0 {
		panic("no return value specified for WriteWorkflow")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, memory.WriteMode) error); ok {
		r0 = rf(ctx, content, mode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store_WriteWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteWorkflow'
type Store_WriteWorkflow_Call struct {
	*mock.Call
}

// WriteWorkflow is a helper method to define mock.On call
//   - ctx context.Context
//   - content string
//   - mode memory.WriteMode
func (_e *Store_Expecter) WriteWorkflow(ctx any, content any, mode any) *Store_WriteWorkflow_Call {
	return &Store_WriteWorkflow_Call{Call: _e.mock.On("WriteWorkflow", ctx, content, mode)}
}

func (_c *Store_WriteWorkflow_Call) Run(run func(ctx context.Context, content string, mode memory.WriteMode)) *Store_WriteWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(memory.WriteMode))
	})
	return _c
}

func (_c *Store_WriteWorkflow_Call) Return(_a0 error) *Store_WriteWorkflow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Store_WriteWorkflow_Call) RunAndReturn(run func(context.Context, string, memory.WriteMode) error) *Store_WriteWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
