// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	detect "github.com/JailtonJunior94/ai-spec-harness/internal/detect"
	skills "github.com/JailtonJunior94/ai-spec-harness/internal/skills"
	mock "github.com/stretchr/testify/mock"
)

// AgentDetector is an autogenerated mock type for the AgentDetector type
type AgentDetector struct {
	mock.Mock
}

type AgentDetector_Expecter struct {
	mock *mock.Mock
}

func (_m *AgentDetector) EXPECT() *AgentDetector_Expecter {
	return &AgentDetector_Expecter{mock: &_m.Mock}
}

// Detect provides a mock function with given fields: ctx, opts
func (_m *AgentDetector) Detect(ctx context.Context, opts detect.DetectOptions) ([]skills.Tool, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Detect")
	}

	var r0 []skills.Tool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, detect.DetectOptions) ([]skills.Tool, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, detect.DetectOptions) []skills.Tool); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]skills.Tool)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, detect.DetectOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AgentDetector_Detect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Detect'
type AgentDetector_Detect_Call struct {
	*mock.Call
}

// Detect is a helper method to define mock.On call
//   - ctx context.Context
//   - opts detect.DetectOptions
func (_e *AgentDetector_Expecter) Detect(ctx any, opts any) *AgentDetector_Detect_Call {
	return &AgentDetector_Detect_Call{Call: _e.mock.On("Detect", ctx, opts)}
}

func (_c *AgentDetector_Detect_Call) Run(run func(ctx context.Context, opts detect.DetectOptions)) *AgentDetector_Detect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(detect.DetectOptions))
	})
	return _c
}

func (_c *AgentDetector_Detect_Call) Return(_a0 []skills.Tool, _a1 error) *AgentDetector_Detect_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AgentDetector_Detect_Call) RunAndReturn(run func(context.Context, detect.DetectOptions) ([]skills.Tool, error)) *AgentDetector_Detect_Call {
	_c.Call.Return(run)
	return _c
}

// NewAgentDetector creates a new instance of AgentDetector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAgentDetector(t interface {
	mock.TestingT
	Cleanup(func())
}) *AgentDetector {
	mock := &AgentDetector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
