// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/JailtonJunior94/ai-spec-harness/internal/skills"
	mock "github.com/stretchr/testify/mock"
)

// NewDetector creates a new instance of Detector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDetector(t interface {
	mock.TestingT
	Cleanup(func())
}) *Detector {
	mock := &Detector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Detector is an autogenerated mock type for the Detector type
type Detector struct {
	mock.Mock
}

type Detector_Expecter struct {
	mock *mock.Mock
}

func (_m *Detector) EXPECT() *Detector_Expecter {
	return &Detector_Expecter{mock: &_m.Mock}
}

// DetectLangs provides a mock function for the type Detector
func (_mock *Detector) DetectLangs(projectDir string) []skills.Lang {
	ret := _mock.Called(projectDir)

	if len(ret) == 0 {
		panic("no return value specified for DetectLangs")
	}

	var r0 []skills.Lang
	if returnFunc, ok := ret.Get(0).(func(string) []skills.Lang); ok {
		r0 = returnFunc(projectDir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]skills.Lang)
		}
	}
	return r0
}

// Detector_DetectLangs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetectLangs'
type Detector_DetectLangs_Call struct {
	*mock.Call
}

// DetectLangs is a helper method to define mock.On call
//   - projectDir string
func (_e *Detector_Expecter) DetectLangs(projectDir any) *Detector_DetectLangs_Call {
	return &Detector_DetectLangs_Call{Call: _e.mock.On("DetectLangs", projectDir)}
}

func (_c *Detector_DetectLangs_Call) Run(run func(projectDir string)) *Detector_DetectLangs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Detector_DetectLangs_Call) Return(langs []skills.Lang) *Detector_DetectLangs_Call {
	_c.Call.Return(langs)
	return _c
}

func (_c *Detector_DetectLangs_Call) RunAndReturn(run func(projectDir string) []skills.Lang) *Detector_DetectLangs_Call {
	_c.Call.Return(run)
	return _c
}

// DetectTools provides a mock function for the type Detector
func (_mock *Detector) DetectTools(projectDir string) []skills.Tool {
	ret := _mock.Called(projectDir)

	if len(ret) == 0 {
		panic("no return value specified for DetectTools")
	}

	var r0 []skills.Tool
	if returnFunc, ok := ret.Get(0).(func(string) []skills.Tool); ok {
		r0 = returnFunc(projectDir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]skills.Tool)
		}
	}
	return r0
}

// Detector_DetectTools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetectTools'
type Detector_DetectTools_Call struct {
	*mock.Call
}

// DetectTools is a helper method to define mock.On call
//   - projectDir string
func (_e *Detector_Expecter) DetectTools(projectDir any) *Detector_DetectTools_Call {
	return &Detector_DetectTools_Call{Call: _e.mock.On("DetectTools", projectDir)}
}

func (_c *Detector_DetectTools_Call) Run(run func(projectDir string)) *Detector_DetectTools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Detector_DetectTools_Call) Return(tools []skills.Tool) *Detector_DetectTools_Call {
	_c.Call.Return(tools)
	return _c
}

func (_c *Detector_DetectTools_Call) RunAndReturn(run func(projectDir string) []skills.Tool) *Detector_DetectTools_Call {
	_c.Call.Return(run)
	return _c
}
