// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewHomeDir creates a new instance of HomeDir. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHomeDir(t interface {
	mock.TestingT
	Cleanup(func())
}) *HomeDir {
	mock := &HomeDir{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HomeDir is an autogenerated mock type for the HomeDir type
type HomeDir struct {
	mock.Mock
}

type HomeDir_Expecter struct {
	mock *mock.Mock
}

func (_m *HomeDir) EXPECT() *HomeDir_Expecter {
	return &HomeDir_Expecter{mock: &_m.Mock}
}

// UserHomeDir provides a mock function for the type HomeDir
func (_mock *HomeDir) UserHomeDir() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserHomeDir")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HomeDir_UserHomeDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserHomeDir'
type HomeDir_UserHomeDir_Call struct {
	*mock.Call
}

// UserHomeDir is a helper method to define mock.On call
func (_e *HomeDir_Expecter) UserHomeDir() *HomeDir_UserHomeDir_Call {
	return &HomeDir_UserHomeDir_Call{Call: _e.mock.On("UserHomeDir")}
}

func (_c *HomeDir_UserHomeDir_Call) Run(run func()) *HomeDir_UserHomeDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HomeDir_UserHomeDir_Call) Return(s string, err error) *HomeDir_UserHomeDir_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *HomeDir_UserHomeDir_Call) RunAndReturn(run func() (string, error)) *HomeDir_UserHomeDir_Call {
	_c.Call.Return(run)
	return _c
}
