// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// IsRepo provides a mock function with given fields: path
func (_m *Repository) IsRepo(path string) bool {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for IsRepo")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Repository_IsRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRepo'
type Repository_IsRepo_Call struct {
	*mock.Call
}

// IsRepo is a helper method to define mock.On call
//   - path string
func (_e *Repository_Expecter) IsRepo(path any) *Repository_IsRepo_Call {
	return &Repository_IsRepo_Call{Call: _e.mock.On("IsRepo", path)}
}

func (_c *Repository_IsRepo_Call) Run(run func(path string)) *Repository_IsRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Repository_IsRepo_Call) Return(_a0 bool) *Repository_IsRepo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_IsRepo_Call) RunAndReturn(run func(string) bool) *Repository_IsRepo_Call {
	_c.Call.Return(run)
	return _c
}

// RemoteURL provides a mock function with given fields: path
func (_m *Repository) RemoteURL(path string) (string, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for RemoteURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_RemoteURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoteURL'
type Repository_RemoteURL_Call struct {
	*mock.Call
}

// RemoteURL is a helper method to define mock.On call
//   - path string
func (_e *Repository_Expecter) RemoteURL(path any) *Repository_RemoteURL_Call {
	return &Repository_RemoteURL_Call{Call: _e.mock.On("RemoteURL", path)}
}

func (_c *Repository_RemoteURL_Call) Run(run func(path string)) *Repository_RemoteURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Repository_RemoteURL_Call) Return(_a0 string, _a1 error) *Repository_RemoteURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_RemoteURL_Call) RunAndReturn(run func(string) (string, error)) *Repository_RemoteURL_Call {
	_c.Call.Return(run)
	return _c
}

// Root provides a mock function with given fields: path
func (_m *Repository) Root(path string) (string, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Root")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Root_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Root'
type Repository_Root_Call struct {
	*mock.Call
}

// Root is a helper method to define mock.On call
//   - path string
func (_e *Repository_Expecter) Root(path any) *Repository_Root_Call {
	return &Repository_Root_Call{Call: _e.mock.On("Root", path)}
}

func (_c *Repository_Root_Call) Run(run func(path string)) *Repository_Root_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Repository_Root_Call) Return(_a0 string, _a1 error) *Repository_Root_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Root_Call) RunAndReturn(run func(string) (string, error)) *Repository_Root_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
