// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/JailtonJunior94/ai-spec-harness/internal/harness"
	mock "github.com/stretchr/testify/mock"
)

// NewLoader creates a new instance of Loader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *Loader {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &Loader{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// Loader is an autogenerated mock type for the Loader type
type Loader struct {
	mock.Mock
}

type Loader_Expecter struct {
	mock *mock.Mock
}

func (_m *Loader) EXPECT() *Loader_Expecter {
	return &Loader_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type Loader
func (_mock *Loader) Load(projectDir string) (harness.Contract, harness.Source, error) {
	ret := _mock.Called(projectDir)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 harness.Contract
	var r1 harness.Source
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (harness.Contract, harness.Source, error)); ok {
		return returnFunc(projectDir)
	}
	if returnFunc, ok := ret.Get(0).(func(string) harness.Contract); ok {
		r0 = returnFunc(projectDir)
	} else {
		r0 = ret.Get(0).(harness.Contract)
	}
	if returnFunc, ok := ret.Get(1).(func(string) harness.Source); ok {
		r1 = returnFunc(projectDir)
	} else {
		r1 = ret.Get(1).(harness.Source)
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(projectDir)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Loader_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type Loader_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - projectDir string
func (_e *Loader_Expecter) Load(projectDir any) *Loader_Load_Call {
	return &Loader_Load_Call{Call: _e.mock.On("Load", projectDir)}
}

func (_c *Loader_Load_Call) Run(run func(projectDir string)) *Loader_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Loader_Load_Call) Return(contract harness.Contract, source harness.Source, err error) *Loader_Load_Call {
	_c.Call.Return(contract, source, err)
	return _c
}

func (_c *Loader_Load_Call) RunAndReturn(run func(projectDir string) (harness.Contract, harness.Source, error)) *Loader_Load_Call {
	_c.Call.Return(run)
	return _c
}
