// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewValidator creates a new instance of Validator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Validator {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &Validator{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// Validator is an autogenerated mock type for the Validator type
type Validator struct {
	mock.Mock
}

type Validator_Expecter struct {
	mock *mock.Mock
}

func (_m *Validator) EXPECT() *Validator_Expecter {
	return &Validator_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type Validator
func (_mock *Validator) Validate(raw map[string]any) error {
	ret := _mock.Called(raw)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(map[string]any) error); ok {
		r0 = returnFunc(raw)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Validator_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type Validator_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - raw map[string]any
func (_e *Validator_Expecter) Validate(raw any) *Validator_Validate_Call {
	return &Validator_Validate_Call{Call: _e.mock.On("Validate", raw)}
}

func (_c *Validator_Validate_Call) Run(run func(raw map[string]any)) *Validator_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]any
		if args[0] != nil {
			arg0 = args[0].(map[string]any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Validator_Validate_Call) Return(err error) *Validator_Validate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Validator_Validate_Call) RunAndReturn(run func(raw map[string]any) error) *Validator_Validate_Call {
	_c.Call.Return(run)
	return _c
}
