// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// Server is an autogenerated mock type for the Server type
type Server struct {
	mock.Mock
}

type Server_Expecter struct {
	mock *mock.Mock
}

func (_m *Server) EXPECT() *Server_Expecter {
	return &Server_Expecter{mock: &_m.Mock}
}

// Serve provides a mock function with given fields: ctx, in, out
func (_m *Server) Serve(ctx context.Context, in io.Reader, out io.Writer) error {
	ret := _m.Called(ctx, in, out)

	if len(ret) == 0 {
		panic("no return value specified for Serve")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader, io.Writer) error); ok {
		r0 = rf(ctx, in, out)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Server_Serve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Serve'
type Server_Serve_Call struct {
	*mock.Call
}

// Serve is a helper method to define mock.On call
//   - ctx context.Context
//   - in io.Reader
//   - out io.Writer
func (_e *Server_Expecter) Serve(ctx any, in any, out any) *Server_Serve_Call {
	return &Server_Serve_Call{Call: _e.mock.On("Serve", ctx, in, out)}
}

func (_c *Server_Serve_Call) Run(run func(ctx context.Context, in io.Reader, out io.Writer)) *Server_Serve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(io.Reader), args[2].(io.Writer))
	})
	return _c
}

func (_c *Server_Serve_Call) Return(_a0 error) *Server_Serve_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Server_Serve_Call) RunAndReturn(run func(context.Context, io.Reader, io.Writer) error) *Server_Serve_Call {
	_c.Call.Return(run)
	return _c
}

// NewServer creates a new instance of Server. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Server {
	mock := &Server{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
