// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewLayerLocker creates a new instance of LayerLocker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLayerLocker(t interface {
	mock.TestingT
	Cleanup(func())
}) *LayerLocker {
	mock := &LayerLocker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LayerLocker is an autogenerated mock type for the LayerLocker type
type LayerLocker struct {
	mock.Mock
}

type LayerLocker_Expecter struct {
	mock *mock.Mock
}

func (_m *LayerLocker) EXPECT() *LayerLocker_Expecter {
	return &LayerLocker_Expecter{mock: &_m.Mock}
}

// Lock provides a mock function for the type LayerLocker
func (_mock *LayerLocker) Lock(path string) (func() error, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Lock")
	}

	var r0 func() error
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (func() error, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) func() error); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func() error)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LayerLocker_Lock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lock'
type LayerLocker_Lock_Call struct {
	*mock.Call
}

// Lock is a helper method to define mock.On call
//   - path string
func (_e *LayerLocker_Expecter) Lock(path any) *LayerLocker_Lock_Call {
	return &LayerLocker_Lock_Call{Call: _e.mock.On("Lock", path)}
}

func (_c *LayerLocker_Lock_Call) Run(run func(path string)) *LayerLocker_Lock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *LayerLocker_Lock_Call) Return(fn func() error, err error) *LayerLocker_Lock_Call {
	_c.Call.Return(fn, err)
	return _c
}

func (_c *LayerLocker_Lock_Call) RunAndReturn(run func(path string) (func() error, error)) *LayerLocker_Lock_Call {
	_c.Call.Return(run)
	return _c
}
