// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/JailtonJunior94/ai-spec-harness/internal/runtime/memory/durable"
	mock "github.com/stretchr/testify/mock"
)

// NewLayer creates a new instance of Layer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Layer {
	mock := &Layer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Layer is an autogenerated mock type for the Layer type
type Layer struct {
	mock.Mock
}

type Layer_Expecter struct {
	mock *mock.Mock
}

func (_m *Layer) EXPECT() *Layer_Expecter {
	return &Layer_Expecter{mock: &_m.Mock}
}

// Archive provides a mock function for the type Layer
func (_mock *Layer) Archive(ctx context.Context, scope durable.Scope, ids []durable.Identity) error {
	ret := _mock.Called(ctx, scope, ids)

	if len(ret) == 0 {
		panic("no return value specified for Archive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, durable.Scope, []durable.Identity) error); ok {
		r0 = returnFunc(ctx, scope, ids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Layer_Archive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Archive'
type Layer_Archive_Call struct {
	*mock.Call
}

// Archive is a helper method to define mock.On call
//   - ctx context.Context
//   - scope durable.Scope
//   - ids []durable.Identity
func (_e *Layer_Expecter) Archive(ctx any, scope any, ids any) *Layer_Archive_Call {
	return &Layer_Archive_Call{Call: _e.mock.On("Archive", ctx, scope, ids)}
}

func (_c *Layer_Archive_Call) Run(run func(ctx context.Context, scope durable.Scope, ids []durable.Identity)) *Layer_Archive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 durable.Scope
		if args[1] != nil {
			arg1 = args[1].(durable.Scope)
		}
		var arg2 []durable.Identity
		if args[2] != nil {
			arg2 = args[2].([]durable.Identity)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Layer_Archive_Call) Return(err error) *Layer_Archive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Layer_Archive_Call) RunAndReturn(run func(ctx context.Context, scope durable.Scope, ids []durable.Identity) error) *Layer_Archive_Call {
	_c.Call.Return(run)
	return _c
}

// Consolidate provides a mock function for the type Layer
func (_mock *Layer) Consolidate(ctx context.Context, scope durable.Scope, newFacts []durable.Fact) (durable.ConsolidationResult, error) {
	ret := _mock.Called(ctx, scope, newFacts)

	if len(ret) == 0 {
		panic("no return value specified for Consolidate")
	}

	var r0 durable.ConsolidationResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, durable.Scope, []durable.Fact) (durable.ConsolidationResult, error)); ok {
		return returnFunc(ctx, scope, newFacts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, durable.Scope, []durable.Fact) durable.ConsolidationResult); ok {
		r0 = returnFunc(ctx, scope, newFacts)
	} else {
		r0 = ret.Get(0).(durable.ConsolidationResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, durable.Scope, []durable.Fact) error); ok {
		r1 = returnFunc(ctx, scope, newFacts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Layer_Consolidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consolidate'
type Layer_Consolidate_Call struct {
	*mock.Call
}

// Consolidate is a helper method to define mock.On call
//   - ctx context.Context
//   - scope durable.Scope
//   - newFacts []durable.Fact
func (_e *Layer_Expecter) Consolidate(ctx any, scope any, newFacts any) *Layer_Consolidate_Call {
	return &Layer_Consolidate_Call{Call: _e.mock.On("Consolidate", ctx, scope, newFacts)}
}

func (_c *Layer_Consolidate_Call) Run(run func(ctx context.Context, scope durable.Scope, newFacts []durable.Fact)) *Layer_Consolidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 durable.Scope
		if args[1] != nil {
			arg1 = args[1].(durable.Scope)
		}
		var arg2 []durable.Fact
		if args[2] != nil {
			arg2 = args[2].([]durable.Fact)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *Layer_Consolidate_Call) Return(consolidationResult durable.ConsolidationResult, err error) *Layer_Consolidate_Call {
	_c.Call.Return(consolidationResult, err)
	return _c
}

func (_c *Layer_Consolidate_Call) RunAndReturn(run func(ctx context.Context, scope durable.Scope, newFacts []durable.Fact) (durable.ConsolidationResult, error)) *Layer_Consolidate_Call {
	_c.Call.Return(run)
	return _c
}

// Promote provides a mock function for the type Layer
func (_mock *Layer) Promote(ctx context.Context, from durable.Scope, to durable.Scope, id durable.Identity) error {
	ret := _mock.Called(ctx, from, to, id)

	if len(ret) == 0 {
		panic("no return value specified for Promote")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, durable.Scope, durable.Scope, durable.Identity) error); ok {
		r0 = returnFunc(ctx, from, to, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Layer_Promote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Promote'
type Layer_Promote_Call struct {
	*mock.Call
}

// Promote is a helper method to define mock.On call
//   - ctx context.Context
//   - from durable.Scope
//   - to durable.Scope
//   - id durable.Identity
func (_e *Layer_Expecter) Promote(ctx any, from any, to any, id any) *Layer_Promote_Call {
	return &Layer_Promote_Call{Call: _e.mock.On("Promote", ctx, from, to, id)}
}

func (_c *Layer_Promote_Call) Run(run func(ctx context.Context, from durable.Scope, to durable.Scope, id durable.Identity)) *Layer_Promote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 durable.Scope
		if args[1] != nil {
			arg1 = args[1].(durable.Scope)
		}
		var arg2 durable.Scope
		if args[2] != nil {
			arg2 = args[2].(durable.Scope)
		}
		var arg3 durable.Identity
		if args[3] != nil {
			arg3 = args[3].(durable.Identity)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *Layer_Promote_Call) Return(err error) *Layer_Promote_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Layer_Promote_Call) RunAndReturn(run func(ctx context.Context, from durable.Scope, to durable.Scope, id durable.Identity) error) *Layer_Promote_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type Layer
func (_mock *Layer) Read(ctx context.Context, scope durable.Scope) ([]durable.Fact, durable.HumanBlock, error) {
	ret := _mock.Called(ctx, scope)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 []durable.Fact
	var r1 durable.HumanBlock
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, durable.Scope) ([]durable.Fact, durable.HumanBlock, error)); ok {
		return returnFunc(ctx, scope)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, durable.Scope) []durable.Fact); ok {
		r0 = returnFunc(ctx, scope)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]durable.Fact)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, durable.Scope) durable.HumanBlock); ok {
		r1 = returnFunc(ctx, scope)
	} else {
		r1 = ret.Get(1).(durable.HumanBlock)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, durable.Scope) error); ok {
		r2 = returnFunc(ctx, scope)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Layer_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type Layer_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - scope durable.Scope
func (_e *Layer_Expecter) Read(ctx any, scope any) *Layer_Read_Call {
	return &Layer_Read_Call{Call: _e.mock.On("Read", ctx, scope)}
}

func (_c *Layer_Read_Call) Run(run func(ctx context.Context, scope durable.Scope)) *Layer_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 durable.Scope
		if args[1] != nil {
			arg1 = args[1].(durable.Scope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Layer_Read_Call) Return(facts []durable.Fact, humanBlock durable.HumanBlock, err error) *Layer_Read_Call {
	_c.Call.Return(facts, humanBlock, err)
	return _c
}

func (_c *Layer_Read_Call) RunAndReturn(run func(ctx context.Context, scope durable.Scope) ([]durable.Fact, durable.HumanBlock, error)) *Layer_Read_Call {
	_c.Call.Return(run)
	return _c
}
