// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/JailtonJunior94/ai-spec-harness/internal/procref"
	mock "github.com/stretchr/testify/mock"
)

// NewLivenessProbe creates a new instance of LivenessProbe. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLivenessProbe(t interface {
	mock.TestingT
	Cleanup(func())
}) *LivenessProbe {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &LivenessProbe{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// LivenessProbe is an autogenerated mock type for the LivenessProbe type
type LivenessProbe struct {
	mock.Mock
}

type LivenessProbe_Expecter struct {
	mock *mock.Mock
}

func (_m *LivenessProbe) EXPECT() *LivenessProbe_Expecter {
	return &LivenessProbe_Expecter{mock: &_m.Mock}
}

// Probe provides a mock function for the type LivenessProbe
func (_mock *LivenessProbe) Probe(ref procref.ProcessRef) procref.LivenessResult {
	ret := _mock.Called(ref)

	if len(ret) == 0 {
		panic("no return value specified for Probe")
	}

	var r0 procref.LivenessResult
	if returnFunc, ok := ret.Get(0).(func(procref.ProcessRef) procref.LivenessResult); ok {
		r0 = returnFunc(ref)
	} else {
		r0 = ret.Get(0).(procref.LivenessResult)
	}
	return r0
}

// LivenessProbe_Probe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Probe'
type LivenessProbe_Probe_Call struct {
	*mock.Call
}

// Probe is a helper method to define mock.On call
//   - ref procref.ProcessRef
func (_e *LivenessProbe_Expecter) Probe(ref any) *LivenessProbe_Probe_Call {
	return &LivenessProbe_Probe_Call{Call: _e.mock.On("Probe", ref)}
}

func (_c *LivenessProbe_Probe_Call) Run(run func(ref procref.ProcessRef)) *LivenessProbe_Probe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 procref.ProcessRef
		if args[0] != nil {
			arg0 = args[0].(procref.ProcessRef)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *LivenessProbe_Probe_Call) Return(livenessResult procref.LivenessResult) *LivenessProbe_Probe_Call {
	_c.Call.Return(livenessResult)
	return _c
}

func (_c *LivenessProbe_Probe_Call) RunAndReturn(run func(ref procref.ProcessRef) procref.LivenessResult) *LivenessProbe_Probe_Call {
	_c.Call.Return(run)
	return _c
}
