// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/JailtonJunior94/ai-spec-harness/internal/runtime/memory/durable"
	mock "github.com/stretchr/testify/mock"
)

// NewPage creates a new instance of Page. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPage(t interface {
	mock.TestingT
	Cleanup(func())
}) *Page {
	mock := &Page{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Page is an autogenerated mock type for the Page type
type Page struct {
	mock.Mock
}

type Page_Expecter struct {
	mock *mock.Mock
}

func (_m *Page) EXPECT() *Page_Expecter {
	return &Page_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type Page
func (_mock *Page) Parse(content []byte) ([]durable.Fact, durable.HumanBlock, error) {
	ret := _mock.Called(content)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 []durable.Fact
	var r1 durable.HumanBlock
	var r2 error
	if returnFunc, ok := ret.Get(0).(func([]byte) ([]durable.Fact, durable.HumanBlock, error)); ok {
		return returnFunc(content)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) []durable.Fact); ok {
		r0 = returnFunc(content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]durable.Fact)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) durable.HumanBlock); ok {
		r1 = returnFunc(content)
	} else {
		r1 = ret.Get(1).(durable.HumanBlock)
	}
	if returnFunc, ok := ret.Get(2).(func([]byte) error); ok {
		r2 = returnFunc(content)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Page_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type Page_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - content []byte
func (_e *Page_Expecter) Parse(content any) *Page_Parse_Call {
	return &Page_Parse_Call{Call: _e.mock.On("Parse", content)}
}

func (_c *Page_Parse_Call) Run(run func(content []byte)) *Page_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Page_Parse_Call) Return(facts []durable.Fact, humanBlock durable.HumanBlock, err error) *Page_Parse_Call {
	_c.Call.Return(facts, humanBlock, err)
	return _c
}

func (_c *Page_Parse_Call) RunAndReturn(run func(content []byte) ([]durable.Fact, durable.HumanBlock, error)) *Page_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// Serialize provides a mock function for the type Page
func (_mock *Page) Serialize(facts []durable.Fact, human durable.HumanBlock) ([]byte, error) {
	ret := _mock.Called(facts, human)

	if len(ret) == 0 {
		panic("no return value specified for Serialize")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]durable.Fact, durable.HumanBlock) ([]byte, error)); ok {
		return returnFunc(facts, human)
	}
	if returnFunc, ok := ret.Get(0).(func([]durable.Fact, durable.HumanBlock) []byte); ok {
		r0 = returnFunc(facts, human)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]durable.Fact, durable.HumanBlock) error); ok {
		r1 = returnFunc(facts, human)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Page_Serialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Serialize'
type Page_Serialize_Call struct {
	*mock.Call
}

// Serialize is a helper method to define mock.On call
//   - facts []durable.Fact
//   - human durable.HumanBlock
func (_e *Page_Expecter) Serialize(facts any, human any) *Page_Serialize_Call {
	return &Page_Serialize_Call{Call: _e.mock.On("Serialize", facts, human)}
}

func (_c *Page_Serialize_Call) Run(run func(facts []durable.Fact, human durable.HumanBlock)) *Page_Serialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []durable.Fact
		if args[0] != nil {
			arg0 = args[0].([]durable.Fact)
		}
		var arg1 durable.HumanBlock
		if args[1] != nil {
			arg1 = args[1].(durable.HumanBlock)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Page_Serialize_Call) Return(bytes []byte, err error) *Page_Serialize_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *Page_Serialize_Call) RunAndReturn(run func(facts []durable.Fact, human durable.HumanBlock) ([]byte, error)) *Page_Serialize_Call {
	_c.Call.Return(run)
	return _c
}
