// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	os "os"

	mock "github.com/stretchr/testify/mock"
)

// FileSystem is an autogenerated mock type for the FileSystem type
type FileSystem struct {
	mock.Mock
}

type FileSystem_Expecter struct {
	mock *mock.Mock
}

func (_m *FileSystem) EXPECT() *FileSystem_Expecter {
	return &FileSystem_Expecter{mock: &_m.Mock}
}

// CopyDir provides a mock function with given fields: src, dst
func (_m *FileSystem) CopyDir(src string, dst string) error {
	ret := _m.Called(src, dst)

	if len(ret) == 0 {
		panic("no return value specified for CopyDir")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(src, dst)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileSystem_CopyDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyDir'
type FileSystem_CopyDir_Call struct {
	*mock.Call
}

// CopyDir is a helper method to define mock.On call
//   - src string
//   - dst string
func (_e *FileSystem_Expecter) CopyDir(src any, dst any) *FileSystem_CopyDir_Call {
	return &FileSystem_CopyDir_Call{Call: _e.mock.On("CopyDir", src, dst)}
}

func (_c *FileSystem_CopyDir_Call) Run(run func(src string, dst string)) *FileSystem_CopyDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *FileSystem_CopyDir_Call) Return(_a0 error) *FileSystem_CopyDir_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileSystem_CopyDir_Call) RunAndReturn(run func(string, string) error) *FileSystem_CopyDir_Call {
	_c.Call.Return(run)
	return _c
}

// CopyFile provides a mock function with given fields: src, dst
func (_m *FileSystem) CopyFile(src string, dst string) error {
	ret := _m.Called(src, dst)

	if len(ret) == 0 {
		panic("no return value specified for CopyFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(src, dst)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileSystem_CopyFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyFile'
type FileSystem_CopyFile_Call struct {
	*mock.Call
}

// CopyFile is a helper method to define mock.On call
//   - src string
//   - dst string
func (_e *FileSystem_Expecter) CopyFile(src any, dst any) *FileSystem_CopyFile_Call {
	return &FileSystem_CopyFile_Call{Call: _e.mock.On("CopyFile", src, dst)}
}

func (_c *FileSystem_CopyFile_Call) Run(run func(src string, dst string)) *FileSystem_CopyFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *FileSystem_CopyFile_Call) Return(_a0 error) *FileSystem_CopyFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileSystem_CopyFile_Call) RunAndReturn(run func(string, string) error) *FileSystem_CopyFile_Call {
	_c.Call.Return(run)
	return _c
}

// DirHash provides a mock function with given fields: path
func (_m *FileSystem) DirHash(path string) (string, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for DirHash")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileSystem_DirHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DirHash'
type FileSystem_DirHash_Call struct {
	*mock.Call
}

// DirHash is a helper method to define mock.On call
//   - path string
func (_e *FileSystem_Expecter) DirHash(path any) *FileSystem_DirHash_Call {
	return &FileSystem_DirHash_Call{Call: _e.mock.On("DirHash", path)}
}

func (_c *FileSystem_DirHash_Call) Run(run func(path string)) *FileSystem_DirHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *FileSystem_DirHash_Call) Return(_a0 string, _a1 error) *FileSystem_DirHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileSystem_DirHash_Call) RunAndReturn(run func(string) (string, error)) *FileSystem_DirHash_Call {
	_c.Call.Return(run)
	return _c
}

// EvalSymlinks provides a mock function with given fields: path
func (_m *FileSystem) EvalSymlinks(path string) (string, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for EvalSymlinks")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileSystem_EvalSymlinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvalSymlinks'
type FileSystem_EvalSymlinks_Call struct {
	*mock.Call
}

// EvalSymlinks is a helper method to define mock.On call
//   - path string
func (_e *FileSystem_Expecter) EvalSymlinks(path any) *FileSystem_EvalSymlinks_Call {
	return &FileSystem_EvalSymlinks_Call{Call: _e.mock.On("EvalSymlinks", path)}
}

func (_c *FileSystem_EvalSymlinks_Call) Run(run func(path string)) *FileSystem_EvalSymlinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *FileSystem_EvalSymlinks_Call) Return(_a0 string, _a1 error) *FileSystem_EvalSymlinks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileSystem_EvalSymlinks_Call) RunAndReturn(run func(string) (string, error)) *FileSystem_EvalSymlinks_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: path
func (_m *FileSystem) Exists(path string) bool {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// FileSystem_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type FileSystem_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - path string
func (_e *FileSystem_Expecter) Exists(path any) *FileSystem_Exists_Call {
	return &FileSystem_Exists_Call{Call: _e.mock.On("Exists", path)}
}

func (_c *FileSystem_Exists_Call) Run(run func(path string)) *FileSystem_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *FileSystem_Exists_Call) Return(_a0 bool) *FileSystem_Exists_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileSystem_Exists_Call) RunAndReturn(run func(string) bool) *FileSystem_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// FileHash provides a mock function with given fields: path
func (_m *FileSystem) FileHash(path string) (string, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for FileHash")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileSystem_FileHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileHash'
type FileSystem_FileHash_Call struct {
	*mock.Call
}

// FileHash is a helper method to define mock.On call
//   - path string
func (_e *FileSystem_Expecter) FileHash(path any) *FileSystem_FileHash_Call {
	return &FileSystem_FileHash_Call{Call: _e.mock.On("FileHash", path)}
}

func (_c *FileSystem_FileHash_Call) Run(run func(path string)) *FileSystem_FileHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *FileSystem_FileHash_Call) Return(_a0 string, _a1 error) *FileSystem_FileHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileSystem_FileHash_Call) RunAndReturn(run func(string) (string, error)) *FileSystem_FileHash_Call {
	_c.Call.Return(run)
	return _c
}

// IsDir provides a mock function with given fields: path
func (_m *FileSystem) IsDir(path string) bool {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for IsDir")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// FileSystem_IsDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDir'
type FileSystem_IsDir_Call struct {
	*mock.Call
}

// IsDir is a helper method to define mock.On call
//   - path string
func (_e *FileSystem_Expecter) IsDir(path any) *FileSystem_IsDir_Call {
	return &FileSystem_IsDir_Call{Call: _e.mock.On("IsDir", path)}
}

func (_c *FileSystem_IsDir_Call) Run(run func(path string)) *FileSystem_IsDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *FileSystem_IsDir_Call) Return(_a0 bool) *FileSystem_IsDir_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileSystem_IsDir_Call) RunAndReturn(run func(string) bool) *FileSystem_IsDir_Call {
	_c.Call.Return(run)
	return _c
}

// IsSymlink provides a mock function with given fields: path
func (_m *FileSystem) IsSymlink(path string) bool {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for IsSymlink")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// FileSystem_IsSymlink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsSymlink'
type FileSystem_IsSymlink_Call struct {
	*mock.Call
}

// IsSymlink is a helper method to define mock.On call
//   - path string
func (_e *FileSystem_Expecter) IsSymlink(path any) *FileSystem_IsSymlink_Call {
	return &FileSystem_IsSymlink_Call{Call: _e.mock.On("IsSymlink", path)}
}

func (_c *FileSystem_IsSymlink_Call) Run(run func(path string)) *FileSystem_IsSymlink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *FileSystem_IsSymlink_Call) Return(_a0 bool) *FileSystem_IsSymlink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileSystem_IsSymlink_Call) RunAndReturn(run func(string) bool) *FileSystem_IsSymlink_Call {
	_c.Call.Return(run)
	return _c
}

// MkdirAll provides a mock function with given fields: path
func (_m *FileSystem) MkdirAll(path string) error {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileSystem_MkdirAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirAll'
type FileSystem_MkdirAll_Call struct {
	*mock.Call
}

// MkdirAll is a helper method to define mock.On call
//   - path string
func (_e *FileSystem_Expecter) MkdirAll(path any) *FileSystem_MkdirAll_Call {
	return &FileSystem_MkdirAll_Call{Call: _e.mock.On("MkdirAll", path)}
}

func (_c *FileSystem_MkdirAll_Call) Run(run func(path string)) *FileSystem_MkdirAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *FileSystem_MkdirAll_Call) Return(_a0 error) *FileSystem_MkdirAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileSystem_MkdirAll_Call) RunAndReturn(run func(string) error) *FileSystem_MkdirAll_Call {
	_c.Call.Return(run)
	return _c
}

// ReadDir provides a mock function with given fields: path
func (_m *FileSystem) ReadDir(path string) ([]os.DirEntry, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []os.DirEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]os.DirEntry, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) []os.DirEntry); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]os.DirEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileSystem_ReadDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadDir'
type FileSystem_ReadDir_Call struct {
	*mock.Call
}

// ReadDir is a helper method to define mock.On call
//   - path string
func (_e *FileSystem_Expecter) ReadDir(path any) *FileSystem_ReadDir_Call {
	return &FileSystem_ReadDir_Call{Call: _e.mock.On("ReadDir", path)}
}

func (_c *FileSystem_ReadDir_Call) Run(run func(path string)) *FileSystem_ReadDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *FileSystem_ReadDir_Call) Return(_a0 []os.DirEntry, _a1 error) *FileSystem_ReadDir_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileSystem_ReadDir_Call) RunAndReturn(run func(string) ([]os.DirEntry, error)) *FileSystem_ReadDir_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function with given fields: path
func (_m *FileSystem) ReadFile(path string) ([]byte, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileSystem_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type FileSystem_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - path string
func (_e *FileSystem_Expecter) ReadFile(path any) *FileSystem_ReadFile_Call {
	return &FileSystem_ReadFile_Call{Call: _e.mock.On("ReadFile", path)}
}

func (_c *FileSystem_ReadFile_Call) Run(run func(path string)) *FileSystem_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *FileSystem_ReadFile_Call) Return(_a0 []byte, _a1 error) *FileSystem_ReadFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileSystem_ReadFile_Call) RunAndReturn(run func(string) ([]byte, error)) *FileSystem_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: path
func (_m *FileSystem) Remove(path string) error {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileSystem_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type FileSystem_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - path string
func (_e *FileSystem_Expecter) Remove(path any) *FileSystem_Remove_Call {
	return &FileSystem_Remove_Call{Call: _e.mock.On("Remove", path)}
}

func (_c *FileSystem_Remove_Call) Run(run func(path string)) *FileSystem_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *FileSystem_Remove_Call) Return(_a0 error) *FileSystem_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileSystem_Remove_Call) RunAndReturn(run func(string) error) *FileSystem_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAll provides a mock function with given fields: path
func (_m *FileSystem) RemoveAll(path string) error {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileSystem_RemoveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAll'
type FileSystem_RemoveAll_Call struct {
	*mock.Call
}

// RemoveAll is a helper method to define mock.On call
//   - path string
func (_e *FileSystem_Expecter) RemoveAll(path any) *FileSystem_RemoveAll_Call {
	return &FileSystem_RemoveAll_Call{Call: _e.mock.On("RemoveAll", path)}
}

func (_c *FileSystem_RemoveAll_Call) Run(run func(path string)) *FileSystem_RemoveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *FileSystem_RemoveAll_Call) Return(_a0 error) *FileSystem_RemoveAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileSystem_RemoveAll_Call) RunAndReturn(run func(string) error) *FileSystem_RemoveAll_Call {
	_c.Call.Return(run)
	return _c
}

// Symlink provides a mock function with given fields: target, link
func (_m *FileSystem) Symlink(target string, link string) error {
	ret := _m.Called(target, link)

	if len(ret) == 0 {
		panic("no return value specified for Symlink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(target, link)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileSystem_Symlink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Symlink'
type FileSystem_Symlink_Call struct {
	*mock.Call
}

// Symlink is a helper method to define mock.On call
//   - target string
//   - link string
func (_e *FileSystem_Expecter) Symlink(target any, link any) *FileSystem_Symlink_Call {
	return &FileSystem_Symlink_Call{Call: _e.mock.On("Symlink", target, link)}
}

func (_c *FileSystem_Symlink_Call) Run(run func(target string, link string)) *FileSystem_Symlink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *FileSystem_Symlink_Call) Return(_a0 error) *FileSystem_Symlink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileSystem_Symlink_Call) RunAndReturn(run func(string, string) error) *FileSystem_Symlink_Call {
	_c.Call.Return(run)
	return _c
}

// Writable provides a mock function with given fields: path
func (_m *FileSystem) Writable(path string) bool {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Writable")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// FileSystem_Writable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Writable'
type FileSystem_Writable_Call struct {
	*mock.Call
}

// Writable is a helper method to define mock.On call
//   - path string
func (_e *FileSystem_Expecter) Writable(path any) *FileSystem_Writable_Call {
	return &FileSystem_Writable_Call{Call: _e.mock.On("Writable", path)}
}

func (_c *FileSystem_Writable_Call) Run(run func(path string)) *FileSystem_Writable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *FileSystem_Writable_Call) Return(_a0 bool) *FileSystem_Writable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileSystem_Writable_Call) RunAndReturn(run func(string) bool) *FileSystem_Writable_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function with given fields: path, data
func (_m *FileSystem) WriteFile(path string, data []byte) error {
	ret := _m.Called(path, data)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(path, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FileSystem_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type FileSystem_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - path string
//   - data []byte
func (_e *FileSystem_Expecter) WriteFile(path any, data any) *FileSystem_WriteFile_Call {
	return &FileSystem_WriteFile_Call{Call: _e.mock.On("WriteFile", path, data)}
}

func (_c *FileSystem_WriteFile_Call) Run(run func(path string, data []byte)) *FileSystem_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte))
	})
	return _c
}

func (_c *FileSystem_WriteFile_Call) Return(_a0 error) *FileSystem_WriteFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FileSystem_WriteFile_Call) RunAndReturn(run func(string, []byte) error) *FileSystem_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewFileSystem creates a new instance of FileSystem. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileSystem(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileSystem {
	mock := &FileSystem{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
