// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	taskloop "github.com/JailtonJunior94/ai-spec-harness/internal/taskloop"
	mock "github.com/stretchr/testify/mock"
)

// AcceptanceGate is an autogenerated mock type for the AcceptanceGate type
type AcceptanceGate struct {
	mock.Mock
}

type AcceptanceGate_Expecter struct {
	mock *mock.Mock
}

func (_m *AcceptanceGate) EXPECT() *AcceptanceGate_Expecter {
	return &AcceptanceGate_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function with given fields: ctx, task, taskFile
func (_m *AcceptanceGate) Verify(ctx context.Context, task taskloop.TaskEntry, taskFile string) (taskloop.AcceptanceReport, error) {
	ret := _m.Called(ctx, task, taskFile)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 taskloop.AcceptanceReport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, taskloop.TaskEntry, string) (taskloop.AcceptanceReport, error)); ok {
		return rf(ctx, task, taskFile)
	}
	if rf, ok := ret.Get(0).(func(context.Context, taskloop.TaskEntry, string) taskloop.AcceptanceReport); ok {
		r0 = rf(ctx, task, taskFile)
	} else {
		r0 = ret.Get(0).(taskloop.AcceptanceReport)
	}

	if rf, ok := ret.Get(1).(func(context.Context, taskloop.TaskEntry, string) error); ok {
		r1 = rf(ctx, task, taskFile)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AcceptanceGate_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type AcceptanceGate_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
//   - task taskloop.TaskEntry
//   - taskFile string
func (_e *AcceptanceGate_Expecter) Verify(ctx any, task any, taskFile any) *AcceptanceGate_Verify_Call {
	return &AcceptanceGate_Verify_Call{Call: _e.mock.On("Verify", ctx, task, taskFile)}
}

func (_c *AcceptanceGate_Verify_Call) Run(run func(ctx context.Context, task taskloop.TaskEntry, taskFile string)) *AcceptanceGate_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(taskloop.TaskEntry), args[2].(string))
	})
	return _c
}

func (_c *AcceptanceGate_Verify_Call) Return(_a0 taskloop.AcceptanceReport, _a1 error) *AcceptanceGate_Verify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AcceptanceGate_Verify_Call) RunAndReturn(run func(context.Context, taskloop.TaskEntry, string) (taskloop.AcceptanceReport, error)) *AcceptanceGate_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewAcceptanceGate creates a new instance of AcceptanceGate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAcceptanceGate(t interface {
	mock.TestingT
	Cleanup(func())
}) *AcceptanceGate {
	mock := &AcceptanceGate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
