// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AgentInvoker is an autogenerated mock type for the AgentInvoker type
type AgentInvoker struct {
	mock.Mock
}

type AgentInvoker_Expecter struct {
	mock *mock.Mock
}

func (_m *AgentInvoker) EXPECT() *AgentInvoker_Expecter {
	return &AgentInvoker_Expecter{mock: &_m.Mock}
}

// BinaryName provides a mock function with no fields
func (_m *AgentInvoker) BinaryName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for BinaryName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// AgentInvoker_BinaryName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BinaryName'
type AgentInvoker_BinaryName_Call struct {
	*mock.Call
}

// BinaryName is a helper method to define mock.On call
func (_e *AgentInvoker_Expecter) BinaryName() *AgentInvoker_BinaryName_Call {
	return &AgentInvoker_BinaryName_Call{Call: _e.mock.On("BinaryName")}
}

func (_c *AgentInvoker_BinaryName_Call) Run(run func()) *AgentInvoker_BinaryName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AgentInvoker_BinaryName_Call) Return(_a0 string) *AgentInvoker_BinaryName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AgentInvoker_BinaryName_Call) RunAndReturn(run func() string) *AgentInvoker_BinaryName_Call {
	_c.Call.Return(run)
	return _c
}

// Invoke provides a mock function with given fields: ctx, prompt, workDir, model
func (_m *AgentInvoker) Invoke(ctx context.Context, prompt string, workDir string, model string) (string, string, int, error) {
	ret := _m.Called(ctx, prompt, workDir, model)

	if len(ret) == 0 {
		panic("no return value specified for Invoke")
	}

	var r0 string
	var r1 string
	var r2 int
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (string, string, int, error)); ok {
		return rf(ctx, prompt, workDir, model)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = rf(ctx, prompt, workDir, model)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) string); ok {
		r1 = rf(ctx, prompt, workDir, model)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string) int); ok {
		r2 = rf(ctx, prompt, workDir, model)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, string, string) error); ok {
		r3 = rf(ctx, prompt, workDir, model)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// AgentInvoker_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type AgentInvoker_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
//   - ctx context.Context
//   - prompt string
//   - workDir string
//   - model string
func (_e *AgentInvoker_Expecter) Invoke(ctx any, prompt any, workDir any, model any) *AgentInvoker_Invoke_Call {
	return &AgentInvoker_Invoke_Call{Call: _e.mock.On("Invoke", ctx, prompt, workDir, model)}
}

func (_c *AgentInvoker_Invoke_Call) Run(run func(ctx context.Context, prompt string, workDir string, model string)) *AgentInvoker_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *AgentInvoker_Invoke_Call) Return(stdout string, stderr string, exitCode int, err error) *AgentInvoker_Invoke_Call {
	_c.Call.Return(stdout, stderr, exitCode, err)
	return _c
}

func (_c *AgentInvoker_Invoke_Call) RunAndReturn(run func(context.Context, string, string, string) (string, string, int, error)) *AgentInvoker_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

// NewAgentInvoker creates a new instance of AgentInvoker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAgentInvoker(t interface {
	mock.TestingT
	Cleanup(func())
}) *AgentInvoker {
	mock := &AgentInvoker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
