// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/JailtonJunior94/ai-spec-harness/internal/taskloop"
	mock "github.com/stretchr/testify/mock"
)

// NewBugfixInvoker creates a new instance of BugfixInvoker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBugfixInvoker(t interface {
	mock.TestingT
	Cleanup(func())
}) *BugfixInvoker {
	mock := &BugfixInvoker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// BugfixInvoker is an autogenerated mock type for the BugfixInvoker type
type BugfixInvoker struct {
	mock.Mock
}

type BugfixInvoker_Expecter struct {
	mock *mock.Mock
}

func (_m *BugfixInvoker) EXPECT() *BugfixInvoker_Expecter {
	return &BugfixInvoker_Expecter{mock: &_m.Mock}
}

// InvokeBugfix provides a mock function for the type BugfixInvoker
func (_mock *BugfixInvoker) InvokeBugfix(ctx context.Context, findings []taskloop.Finding, diff string) (string, error) {
	ret := _mock.Called(ctx, findings, diff)

	if len(ret) == 0 {
		panic("no return value specified for InvokeBugfix")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []taskloop.Finding, string) (string, error)); ok {
		return returnFunc(ctx, findings, diff)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []taskloop.Finding, string) string); ok {
		r0 = returnFunc(ctx, findings, diff)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []taskloop.Finding, string) error); ok {
		r1 = returnFunc(ctx, findings, diff)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// BugfixInvoker_InvokeBugfix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvokeBugfix'
type BugfixInvoker_InvokeBugfix_Call struct {
	*mock.Call
}

// InvokeBugfix is a helper method to define mock.On call
//   - ctx context.Context
//   - findings []taskloop.Finding
//   - diff string
func (_e *BugfixInvoker_Expecter) InvokeBugfix(ctx any, findings any, diff any) *BugfixInvoker_InvokeBugfix_Call {
	return &BugfixInvoker_InvokeBugfix_Call{Call: _e.mock.On("InvokeBugfix", ctx, findings, diff)}
}

func (_c *BugfixInvoker_InvokeBugfix_Call) Run(run func(ctx context.Context, findings []taskloop.Finding, diff string)) *BugfixInvoker_InvokeBugfix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []taskloop.Finding
		if args[1] != nil {
			arg1 = args[1].([]taskloop.Finding)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *BugfixInvoker_InvokeBugfix_Call) Return(s string, err error) *BugfixInvoker_InvokeBugfix_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *BugfixInvoker_InvokeBugfix_Call) RunAndReturn(run func(ctx context.Context, findings []taskloop.Finding, diff string) (string, error)) *BugfixInvoker_InvokeBugfix_Call {
	_c.Call.Return(run)
	return _c
}
