// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CommandRunner is an autogenerated mock type for the CommandRunner type
type CommandRunner struct {
	mock.Mock
}

type CommandRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *CommandRunner) EXPECT() *CommandRunner_Expecter {
	return &CommandRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields: ctx, name, args
func (_m *CommandRunner) Run(ctx context.Context, name string, args ...string) (string, error) {
	_va := make([]any, len(args))
	for _i := range args {
		_va[_i] = args[_i]
	}
	var _ca []any
	_ca = append(_ca, ctx, name)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...string) (string, error)); ok {
		return rf(ctx, name, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...string) string); ok {
		r0 = rf(ctx, name, args...)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...string) error); ok {
		r1 = rf(ctx, name, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommandRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type CommandRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - args ...string
func (_e *CommandRunner_Expecter) Run(ctx any, name any, args ...any) *CommandRunner_Run_Call {
	return &CommandRunner_Run_Call{Call: _e.mock.On("Run",
		append([]any{ctx, name}, args...)...)}
}

func (_c *CommandRunner_Run_Call) Run(run func(ctx context.Context, name string, args ...string)) *CommandRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *CommandRunner_Run_Call) Return(output string, err error) *CommandRunner_Run_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *CommandRunner_Run_Call) RunAndReturn(run func(context.Context, string, ...string) (string, error)) *CommandRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewCommandRunner creates a new instance of CommandRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommandRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommandRunner {
	mock := &CommandRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
