// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewCommandRunner creates a new instance of CommandRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommandRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommandRunner {
	mock := &CommandRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CommandRunner is an autogenerated mock type for the CommandRunner type
type CommandRunner struct {
	mock.Mock
}

type CommandRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *CommandRunner) EXPECT() *CommandRunner_Expecter {
	return &CommandRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type CommandRunner
func (_mock *CommandRunner) Run(ctx context.Context, name string, args ...string) (string, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, name, args)
	} else {
		tmpRet = _mock.Called(ctx, name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) (string, error)); ok {
		return returnFunc(ctx, name, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...string) string); ok {
		r0 = returnFunc(ctx, name, args...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...string) error); ok {
		r1 = returnFunc(ctx, name, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CommandRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type CommandRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - args ...string
func (_e *CommandRunner_Expecter) Run(ctx any, name any, args ...any) *CommandRunner_Run_Call {
	return &CommandRunner_Run_Call{Call: _e.mock.On("Run",
		append([]any{ctx, name}, args...)...)}
}

func (_c *CommandRunner_Run_Call) Run(run func(ctx context.Context, name string, args ...string)) *CommandRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *CommandRunner_Run_Call) Return(output string, err error) *CommandRunner_Run_Call {
	_c.Call.Return(output, err)
	return _c
}

func (_c *CommandRunner_Run_Call) RunAndReturn(run func(ctx context.Context, name string, args ...string) (string, error)) *CommandRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}
