// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DiffCapturer is an autogenerated mock type for the DiffCapturer type
type DiffCapturer struct {
	mock.Mock
}

type DiffCapturer_Expecter struct {
	mock *mock.Mock
}

func (_m *DiffCapturer) EXPECT() *DiffCapturer_Expecter {
	return &DiffCapturer_Expecter{mock: &_m.Mock}
}

// CaptureDiff provides a mock function with given fields: ctx
func (_m *DiffCapturer) CaptureDiff(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CaptureDiff")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DiffCapturer_CaptureDiff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CaptureDiff'
type DiffCapturer_CaptureDiff_Call struct {
	*mock.Call
}

// CaptureDiff is a helper method to define mock.On call
//   - ctx context.Context
func (_e *DiffCapturer_Expecter) CaptureDiff(ctx any) *DiffCapturer_CaptureDiff_Call {
	return &DiffCapturer_CaptureDiff_Call{Call: _e.mock.On("CaptureDiff", ctx)}
}

func (_c *DiffCapturer_CaptureDiff_Call) Run(run func(ctx context.Context)) *DiffCapturer_CaptureDiff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *DiffCapturer_CaptureDiff_Call) Return(_a0 string, _a1 error) *DiffCapturer_CaptureDiff_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DiffCapturer_CaptureDiff_Call) RunAndReturn(run func(context.Context) (string, error)) *DiffCapturer_CaptureDiff_Call {
	_c.Call.Return(run)
	return _c
}

// NewDiffCapturer creates a new instance of DiffCapturer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDiffCapturer(t interface {
	mock.TestingT
	Cleanup(func())
}) *DiffCapturer {
	mock := &DiffCapturer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
