// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	taskloop "github.com/JailtonJunior94/ai-spec-harness/internal/taskloop"
	mock "github.com/stretchr/testify/mock"
)

// EvidenceRecorder is an autogenerated mock type for the EvidenceRecorder type
type EvidenceRecorder struct {
	mock.Mock
}

type EvidenceRecorder_Expecter struct {
	mock *mock.Mock
}

func (_m *EvidenceRecorder) EXPECT() *EvidenceRecorder_Expecter {
	return &EvidenceRecorder_Expecter{mock: &_m.Mock}
}

// Append provides a mock function with given fields: ctx, taskFile, report
func (_m *EvidenceRecorder) Append(ctx context.Context, taskFile string, report taskloop.AcceptanceReport) error {
	ret := _m.Called(ctx, taskFile, report)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, taskloop.AcceptanceReport) error); ok {
		r0 = rf(ctx, taskFile, report)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EvidenceRecorder_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type EvidenceRecorder_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - ctx context.Context
//   - taskFile string
//   - report taskloop.AcceptanceReport
func (_e *EvidenceRecorder_Expecter) Append(ctx any, taskFile any, report any) *EvidenceRecorder_Append_Call {
	return &EvidenceRecorder_Append_Call{Call: _e.mock.On("Append", ctx, taskFile, report)}
}

func (_c *EvidenceRecorder_Append_Call) Run(run func(ctx context.Context, taskFile string, report taskloop.AcceptanceReport)) *EvidenceRecorder_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(taskloop.AcceptanceReport))
	})
	return _c
}

func (_c *EvidenceRecorder_Append_Call) Return(_a0 error) *EvidenceRecorder_Append_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EvidenceRecorder_Append_Call) RunAndReturn(run func(context.Context, string, taskloop.AcceptanceReport) error) *EvidenceRecorder_Append_Call {
	_c.Call.Return(run)
	return _c
}

// NewEvidenceRecorder creates a new instance of EvidenceRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEvidenceRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *EvidenceRecorder {
	mock := &EvidenceRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
