// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/JailtonJunior94/ai-spec-harness/internal/taskloop"
	mock "github.com/stretchr/testify/mock"
)

// NewFinalReviewer creates a new instance of FinalReviewer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFinalReviewer(t interface {
	mock.TestingT
	Cleanup(func())
}) *FinalReviewer {
	mock := &FinalReviewer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FinalReviewer is an autogenerated mock type for the FinalReviewer type
type FinalReviewer struct {
	mock.Mock
}

type FinalReviewer_Expecter struct {
	mock *mock.Mock
}

func (_m *FinalReviewer) EXPECT() *FinalReviewer_Expecter {
	return &FinalReviewer_Expecter{mock: &_m.Mock}
}

// ReviewConsolidated provides a mock function for the type FinalReviewer
func (_mock *FinalReviewer) ReviewConsolidated(ctx context.Context, diff string) (taskloop.FinalReviewResult, error) {
	ret := _mock.Called(ctx, diff)

	if len(ret) == 0 {
		panic("no return value specified for ReviewConsolidated")
	}

	var r0 taskloop.FinalReviewResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (taskloop.FinalReviewResult, error)); ok {
		return returnFunc(ctx, diff)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) taskloop.FinalReviewResult); ok {
		r0 = returnFunc(ctx, diff)
	} else {
		r0 = ret.Get(0).(taskloop.FinalReviewResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, diff)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FinalReviewer_ReviewConsolidated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReviewConsolidated'
type FinalReviewer_ReviewConsolidated_Call struct {
	*mock.Call
}

// ReviewConsolidated is a helper method to define mock.On call
//   - ctx context.Context
//   - diff string
func (_e *FinalReviewer_Expecter) ReviewConsolidated(ctx any, diff any) *FinalReviewer_ReviewConsolidated_Call {
	return &FinalReviewer_ReviewConsolidated_Call{Call: _e.mock.On("ReviewConsolidated", ctx, diff)}
}

func (_c *FinalReviewer_ReviewConsolidated_Call) Run(run func(ctx context.Context, diff string)) *FinalReviewer_ReviewConsolidated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FinalReviewer_ReviewConsolidated_Call) Return(finalReviewResult taskloop.FinalReviewResult, err error) *FinalReviewer_ReviewConsolidated_Call {
	_c.Call.Return(finalReviewResult, err)
	return _c
}

func (_c *FinalReviewer_ReviewConsolidated_Call) RunAndReturn(run func(ctx context.Context, diff string) (taskloop.FinalReviewResult, error)) *FinalReviewer_ReviewConsolidated_Call {
	_c.Call.Return(run)
	return _c
}
