// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// LiveOutputSetter is an autogenerated mock type for the LiveOutputSetter type
type LiveOutputSetter struct {
	mock.Mock
}

type LiveOutputSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *LiveOutputSetter) EXPECT() *LiveOutputSetter_Expecter {
	return &LiveOutputSetter_Expecter{mock: &_m.Mock}
}

// SetLiveOutput provides a mock function with given fields: w
func (_m *LiveOutputSetter) SetLiveOutput(w io.Writer) {
	_m.Called(w)
}

// LiveOutputSetter_SetLiveOutput_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLiveOutput'
type LiveOutputSetter_SetLiveOutput_Call struct {
	*mock.Call
}

// SetLiveOutput is a helper method to define mock.On call
//   - w io.Writer
func (_e *LiveOutputSetter_Expecter) SetLiveOutput(w any) *LiveOutputSetter_SetLiveOutput_Call {
	return &LiveOutputSetter_SetLiveOutput_Call{Call: _e.mock.On("SetLiveOutput", w)}
}

func (_c *LiveOutputSetter_SetLiveOutput_Call) Run(run func(w io.Writer)) *LiveOutputSetter_SetLiveOutput_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Writer))
	})
	return _c
}

func (_c *LiveOutputSetter_SetLiveOutput_Call) Return() *LiveOutputSetter_SetLiveOutput_Call {
	_c.Call.Return()
	return _c
}

func (_c *LiveOutputSetter_SetLiveOutput_Call) RunAndReturn(run func(io.Writer)) *LiveOutputSetter_SetLiveOutput_Call {
	_c.Run(run)
	return _c
}

// NewLiveOutputSetter creates a new instance of LiveOutputSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLiveOutputSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *LiveOutputSetter {
	mock := &LiveOutputSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
