// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/JailtonJunior94/ai-spec-harness/internal/taskloop"
	mock "github.com/stretchr/testify/mock"
)

// NewPrompter creates a new instance of Prompter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPrompter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Prompter {
	mock := &Prompter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Prompter is an autogenerated mock type for the Prompter type
type Prompter struct {
	mock.Mock
}

type Prompter_Expecter struct {
	mock *mock.Mock
}

func (_m *Prompter) EXPECT() *Prompter_Expecter {
	return &Prompter_Expecter{mock: &_m.Mock}
}

// Ask provides a mock function for the type Prompter
func (_mock *Prompter) Ask(ctx context.Context, finding taskloop.Finding) (taskloop.ResolutionAction, string, error) {
	ret := _mock.Called(ctx, finding)

	if len(ret) == 0 {
		panic("no return value specified for Ask")
	}

	var r0 taskloop.ResolutionAction
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, taskloop.Finding) (taskloop.ResolutionAction, string, error)); ok {
		return returnFunc(ctx, finding)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, taskloop.Finding) taskloop.ResolutionAction); ok {
		r0 = returnFunc(ctx, finding)
	} else {
		r0 = ret.Get(0).(taskloop.ResolutionAction)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, taskloop.Finding) string); ok {
		r1 = returnFunc(ctx, finding)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, taskloop.Finding) error); ok {
		r2 = returnFunc(ctx, finding)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// Prompter_Ask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ask'
type Prompter_Ask_Call struct {
	*mock.Call
}

// Ask is a helper method to define mock.On call
//   - ctx context.Context
//   - finding taskloop.Finding
func (_e *Prompter_Expecter) Ask(ctx any, finding any) *Prompter_Ask_Call {
	return &Prompter_Ask_Call{Call: _e.mock.On("Ask", ctx, finding)}
}

func (_c *Prompter_Ask_Call) Run(run func(ctx context.Context, finding taskloop.Finding)) *Prompter_Ask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 taskloop.Finding
		if args[1] != nil {
			arg1 = args[1].(taskloop.Finding)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Prompter_Ask_Call) Return(resolutionAction taskloop.ResolutionAction, s string, err error) *Prompter_Ask_Call {
	_c.Call.Return(resolutionAction, s, err)
	return _c
}

func (_c *Prompter_Ask_Call) RunAndReturn(run func(ctx context.Context, finding taskloop.Finding) (taskloop.ResolutionAction, string, error)) *Prompter_Ask_Call {
	_c.Call.Return(run)
	return _c
}
