// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	taskloop "github.com/JailtonJunior94/ai-spec-harness/internal/taskloop"
	mock "github.com/stretchr/testify/mock"
)

// Prompter is an autogenerated mock type for the Prompter type
type Prompter struct {
	mock.Mock
}

type Prompter_Expecter struct {
	mock *mock.Mock
}

func (_m *Prompter) EXPECT() *Prompter_Expecter {
	return &Prompter_Expecter{mock: &_m.Mock}
}

// Ask provides a mock function with given fields: ctx, finding
func (_m *Prompter) Ask(ctx context.Context, finding taskloop.Finding) (taskloop.ResolutionAction, string, error) {
	ret := _m.Called(ctx, finding)

	if len(ret) == 0 {
		panic("no return value specified for Ask")
	}

	var r0 taskloop.ResolutionAction
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, taskloop.Finding) (taskloop.ResolutionAction, string, error)); ok {
		return rf(ctx, finding)
	}
	if rf, ok := ret.Get(0).(func(context.Context, taskloop.Finding) taskloop.ResolutionAction); ok {
		r0 = rf(ctx, finding)
	} else {
		r0 = ret.Get(0).(taskloop.ResolutionAction)
	}

	if rf, ok := ret.Get(1).(func(context.Context, taskloop.Finding) string); ok {
		r1 = rf(ctx, finding)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, taskloop.Finding) error); ok {
		r2 = rf(ctx, finding)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Prompter_Ask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ask'
type Prompter_Ask_Call struct {
	*mock.Call
}

// Ask is a helper method to define mock.On call
//   - ctx context.Context
//   - finding taskloop.Finding
func (_e *Prompter_Expecter) Ask(ctx any, finding any) *Prompter_Ask_Call {
	return &Prompter_Ask_Call{Call: _e.mock.On("Ask", ctx, finding)}
}

func (_c *Prompter_Ask_Call) Run(run func(ctx context.Context, finding taskloop.Finding)) *Prompter_Ask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(taskloop.Finding))
	})
	return _c
}

func (_c *Prompter_Ask_Call) Return(_a0 taskloop.ResolutionAction, _a1 string, _a2 error) *Prompter_Ask_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Prompter_Ask_Call) RunAndReturn(run func(context.Context, taskloop.Finding) (taskloop.ResolutionAction, string, error)) *Prompter_Ask_Call {
	_c.Call.Return(run)
	return _c
}

// NewPrompter creates a new instance of Prompter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPrompter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Prompter {
	mock := &Prompter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
