// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	taskloop "github.com/JailtonJunior94/ai-spec-harness/internal/taskloop"
	mock "github.com/stretchr/testify/mock"
)

// ReservationPlanner is an autogenerated mock type for the ReservationPlanner type
type ReservationPlanner struct {
	mock.Mock
}

type ReservationPlanner_Expecter struct {
	mock *mock.Mock
}

func (_m *ReservationPlanner) EXPECT() *ReservationPlanner_Expecter {
	return &ReservationPlanner_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function with given fields: ctx, findings
func (_m *ReservationPlanner) Resolve(ctx context.Context, findings []taskloop.Finding) (taskloop.ActionPlan, error) {
	ret := _m.Called(ctx, findings)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 taskloop.ActionPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []taskloop.Finding) (taskloop.ActionPlan, error)); ok {
		return rf(ctx, findings)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []taskloop.Finding) taskloop.ActionPlan); ok {
		r0 = rf(ctx, findings)
	} else {
		r0 = ret.Get(0).(taskloop.ActionPlan)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []taskloop.Finding) error); ok {
		r1 = rf(ctx, findings)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReservationPlanner_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type ReservationPlanner_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - findings []taskloop.Finding
func (_e *ReservationPlanner_Expecter) Resolve(ctx any, findings any) *ReservationPlanner_Resolve_Call {
	return &ReservationPlanner_Resolve_Call{Call: _e.mock.On("Resolve", ctx, findings)}
}

func (_c *ReservationPlanner_Resolve_Call) Run(run func(ctx context.Context, findings []taskloop.Finding)) *ReservationPlanner_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]taskloop.Finding))
	})
	return _c
}

func (_c *ReservationPlanner_Resolve_Call) Return(_a0 taskloop.ActionPlan, _a1 error) *ReservationPlanner_Resolve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReservationPlanner_Resolve_Call) RunAndReturn(run func(context.Context, []taskloop.Finding) (taskloop.ActionPlan, error)) *ReservationPlanner_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// NewReservationPlanner creates a new instance of ReservationPlanner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReservationPlanner(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReservationPlanner {
	mock := &ReservationPlanner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
