// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	taskloop "github.com/JailtonJunior94/ai-spec-harness/internal/taskloop"
	mock "github.com/stretchr/testify/mock"
)

// TaskExecutor is an autogenerated mock type for the TaskExecutor type
type TaskExecutor struct {
	mock.Mock
}

type TaskExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskExecutor) EXPECT() *TaskExecutor_Expecter {
	return &TaskExecutor_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, task, taskFile, prdFolder, workDir
func (_m *TaskExecutor) Execute(ctx context.Context, task taskloop.TaskEntry, taskFile string, prdFolder string, workDir string) error {
	ret := _m.Called(ctx, task, taskFile, prdFolder, workDir)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, taskloop.TaskEntry, string, string, string) error); ok {
		r0 = rf(ctx, task, taskFile, prdFolder, workDir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskExecutor_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type TaskExecutor_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - task taskloop.TaskEntry
//   - taskFile string
//   - prdFolder string
//   - workDir string
func (_e *TaskExecutor_Expecter) Execute(ctx any, task any, taskFile any, prdFolder any, workDir any) *TaskExecutor_Execute_Call {
	return &TaskExecutor_Execute_Call{Call: _e.mock.On("Execute", ctx, task, taskFile, prdFolder, workDir)}
}

func (_c *TaskExecutor_Execute_Call) Run(run func(ctx context.Context, task taskloop.TaskEntry, taskFile string, prdFolder string, workDir string)) *TaskExecutor_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(taskloop.TaskEntry), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *TaskExecutor_Execute_Call) Return(_a0 error) *TaskExecutor_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TaskExecutor_Execute_Call) RunAndReturn(run func(context.Context, taskloop.TaskEntry, string, string, string) error) *TaskExecutor_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskExecutor creates a new instance of TaskExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskExecutor {
	mock := &TaskExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
