// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	taskloop "github.com/JailtonJunior94/ai-spec-harness/internal/taskloop"
	mock "github.com/stretchr/testify/mock"
)

// TaskSelector is an autogenerated mock type for the TaskSelector type
type TaskSelector struct {
	mock.Mock
}

type TaskSelector_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskSelector) EXPECT() *TaskSelector_Expecter {
	return &TaskSelector_Expecter{mock: &_m.Mock}
}

// Next provides a mock function with given fields: ctx, prdFolder
func (_m *TaskSelector) Next(ctx context.Context, prdFolder string) (*taskloop.TaskEntry, error) {
	ret := _m.Called(ctx, prdFolder)

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 *taskloop.TaskEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*taskloop.TaskEntry, error)); ok {
		return rf(ctx, prdFolder)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *taskloop.TaskEntry); ok {
		r0 = rf(ctx, prdFolder)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*taskloop.TaskEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, prdFolder)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskSelector_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type TaskSelector_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
//   - ctx context.Context
//   - prdFolder string
func (_e *TaskSelector_Expecter) Next(ctx any, prdFolder any) *TaskSelector_Next_Call {
	return &TaskSelector_Next_Call{Call: _e.mock.On("Next", ctx, prdFolder)}
}

func (_c *TaskSelector_Next_Call) Run(run func(ctx context.Context, prdFolder string)) *TaskSelector_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TaskSelector_Next_Call) Return(_a0 *taskloop.TaskEntry, _a1 error) *TaskSelector_Next_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskSelector_Next_Call) RunAndReturn(run func(context.Context, string) (*taskloop.TaskEntry, error)) *TaskSelector_Next_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskSelector creates a new instance of TaskSelector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskSelector(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskSelector {
	mock := &TaskSelector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
