// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	triggers "github.com/JailtonJunior94/ai-spec-harness/internal/triggers"
	mock "github.com/stretchr/testify/mock"
)

// Loader is an autogenerated mock type for the Loader type
type Loader struct {
	mock.Mock
}

type Loader_Expecter struct {
	mock *mock.Mock
}

func (_m *Loader) EXPECT() *Loader_Expecter {
	return &Loader_Expecter{mock: &_m.Mock}
}

// Load provides a mock function with given fields: lang
func (_m *Loader) Load(lang string) ([]triggers.Trigger, error) {
	ret := _m.Called(lang)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 []triggers.Trigger
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]triggers.Trigger, error)); ok {
		return rf(lang)
	}
	if rf, ok := ret.Get(0).(func(string) []triggers.Trigger); ok {
		r0 = rf(lang)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]triggers.Trigger)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(lang)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Loader_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type Loader_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - lang string
func (_e *Loader_Expecter) Load(lang any) *Loader_Load_Call {
	return &Loader_Load_Call{Call: _e.mock.On("Load", lang)}
}

func (_c *Loader_Load_Call) Run(run func(lang string)) *Loader_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Loader_Load_Call) Return(_a0 []triggers.Trigger, _a1 error) *Loader_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Loader_Load_Call) RunAndReturn(run func(string) ([]triggers.Trigger, error)) *Loader_Load_Call {
	_c.Call.Return(run)
	return _c
}

// NewLoader creates a new instance of Loader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *Loader {
	mock := &Loader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
