// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"encoding/json"

	"github.com/JailtonJunior94/ai-spec-harness/internal/runtime/events"
	mock "github.com/stretchr/testify/mock"
)

// NewMetricsExtractor creates a new instance of MetricsExtractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsExtractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsExtractor {
	mock := &MetricsExtractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MetricsExtractor is an autogenerated mock type for the MetricsExtractor type
type MetricsExtractor struct {
	mock.Mock
}

type MetricsExtractor_Expecter struct {
	mock *mock.Mock
}

func (_m *MetricsExtractor) EXPECT() *MetricsExtractor_Expecter {
	return &MetricsExtractor_Expecter{mock: &_m.Mock}
}

// Extract provides a mock function for the type MetricsExtractor
func (_mock *MetricsExtractor) Extract(raw json.RawMessage) events.MetricSet {
	ret := _mock.Called(raw)

	if len(ret) == 0 {
		panic("no return value specified for Extract")
	}

	var r0 events.MetricSet
	if returnFunc, ok := ret.Get(0).(func(json.RawMessage) events.MetricSet); ok {
		r0 = returnFunc(raw)
	} else {
		r0 = ret.Get(0).(events.MetricSet)
	}
	return r0
}

// MetricsExtractor_Extract_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extract'
type MetricsExtractor_Extract_Call struct {
	*mock.Call
}

// Extract is a helper method to define mock.On call
//   - raw json.RawMessage
func (_e *MetricsExtractor_Expecter) Extract(raw any) *MetricsExtractor_Extract_Call {
	return &MetricsExtractor_Extract_Call{Call: _e.mock.On("Extract", raw)}
}

func (_c *MetricsExtractor_Extract_Call) Run(run func(raw json.RawMessage)) *MetricsExtractor_Extract_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 json.RawMessage
		if args[0] != nil {
			arg0 = args[0].(json.RawMessage)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MetricsExtractor_Extract_Call) Return(metricSet events.MetricSet) *MetricsExtractor_Extract_Call {
	_c.Call.Return(metricSet)
	return _c
}

func (_c *MetricsExtractor_Extract_Call) RunAndReturn(run func(raw json.RawMessage) events.MetricSet) *MetricsExtractor_Extract_Call {
	_c.Call.Return(run)
	return _c
}
