// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	agents "github.com/JailtonJunior94/ai-spec-harness/internal/agents"
	mock "github.com/stretchr/testify/mock"
)

// Registry is an autogenerated mock type for the Registry type
type Registry struct {
	mock.Mock
}

type Registry_Expecter struct {
	mock *mock.Mock
}

func (_m *Registry) EXPECT() *Registry_Expecter {
	return &Registry_Expecter{mock: &_m.Mock}
}

// Discover provides a mock function with given fields: ctx
func (_m *Registry) Discover(ctx context.Context) ([]agents.ResolvedAgent, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Discover")
	}

	var r0 []agents.ResolvedAgent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]agents.ResolvedAgent, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []agents.ResolvedAgent); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]agents.ResolvedAgent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Registry_Discover_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Discover'
type Registry_Discover_Call struct {
	*mock.Call
}

// Discover is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Registry_Expecter) Discover(ctx any) *Registry_Discover_Call {
	return &Registry_Discover_Call{Call: _e.mock.On("Discover", ctx)}
}

func (_c *Registry_Discover_Call) Run(run func(ctx context.Context)) *Registry_Discover_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Registry_Discover_Call) Return(_a0 []agents.ResolvedAgent, _a1 error) *Registry_Discover_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Registry_Discover_Call) RunAndReturn(run func(context.Context) ([]agents.ResolvedAgent, error)) *Registry_Discover_Call {
	_c.Call.Return(run)
	return _c
}

// Resolve provides a mock function with given fields: name
func (_m *Registry) Resolve(name string) (agents.ResolvedAgent, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 agents.ResolvedAgent
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (agents.ResolvedAgent, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) agents.ResolvedAgent); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(agents.ResolvedAgent)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Registry_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type Registry_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - name string
func (_e *Registry_Expecter) Resolve(name any) *Registry_Resolve_Call {
	return &Registry_Resolve_Call{Call: _e.mock.On("Resolve", name)}
}

func (_c *Registry_Resolve_Call) Run(run func(name string)) *Registry_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Registry_Resolve_Call) Return(_a0 agents.ResolvedAgent, _a1 error) *Registry_Resolve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Registry_Resolve_Call) RunAndReturn(run func(string) (agents.ResolvedAgent, error)) *Registry_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// NewRegistry creates a new instance of Registry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *Registry {
	mock := &Registry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
