// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewTokenizer creates a new instance of Tokenizer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenizer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Tokenizer {
	mock := &Tokenizer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Tokenizer is an autogenerated mock type for the Tokenizer type
type Tokenizer struct {
	mock.Mock
}

type Tokenizer_Expecter struct {
	mock *mock.Mock
}

func (_m *Tokenizer) EXPECT() *Tokenizer_Expecter {
	return &Tokenizer_Expecter{mock: &_m.Mock}
}

// EstimateTokens provides a mock function for the type Tokenizer
func (_mock *Tokenizer) EstimateTokens(text string) int {
	ret := _mock.Called(text)

	if len(ret) == 0 {
		panic("no return value specified for EstimateTokens")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func(string) int); ok {
		r0 = returnFunc(text)
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// Tokenizer_EstimateTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EstimateTokens'
type Tokenizer_EstimateTokens_Call struct {
	*mock.Call
}

// EstimateTokens is a helper method to define mock.On call
//   - text string
func (_e *Tokenizer_Expecter) EstimateTokens(text any) *Tokenizer_EstimateTokens_Call {
	return &Tokenizer_EstimateTokens_Call{Call: _e.mock.On("EstimateTokens", text)}
}

func (_c *Tokenizer_EstimateTokens_Call) Run(run func(text string)) *Tokenizer_EstimateTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Tokenizer_EstimateTokens_Call) Return(n int) *Tokenizer_EstimateTokens_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *Tokenizer_EstimateTokens_Call) RunAndReturn(run func(text string) int) *Tokenizer_EstimateTokens_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type Tokenizer
func (_mock *Tokenizer) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Tokenizer_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Tokenizer_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Tokenizer_Expecter) Name() *Tokenizer_Name_Call {
	return &Tokenizer_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *Tokenizer_Name_Call) Run(run func()) *Tokenizer_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Tokenizer_Name_Call) Return(s string) *Tokenizer_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Tokenizer_Name_Call) RunAndReturn(run func() string) *Tokenizer_Name_Call {
	_c.Call.Return(run)
	return _c
}
