// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/JailtonJunior94/ai-spec-harness/internal/runtime/client"
	mock "github.com/stretchr/testify/mock"
)

// NewClientFactory creates a new instance of ClientFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientFactory {
	mock := &ClientFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ClientFactory is an autogenerated mock type for the ClientFactory type
type ClientFactory struct {
	mock.Mock
}

type ClientFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientFactory) EXPECT() *ClientFactory_Expecter {
	return &ClientFactory_Expecter{mock: &_m.Mock}
}

// New provides a mock function for the type ClientFactory
func (_mock *ClientFactory) New(workDir string) client.Client {
	ret := _mock.Called(workDir)

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 client.Client
	if returnFunc, ok := ret.Get(0).(func(string) client.Client); ok {
		r0 = returnFunc(workDir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}
	return r0
}

// ClientFactory_New_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'New'
type ClientFactory_New_Call struct {
	*mock.Call
}

// New is a helper method to define mock.On call
//   - workDir string
func (_e *ClientFactory_Expecter) New(workDir any) *ClientFactory_New_Call {
	return &ClientFactory_New_Call{Call: _e.mock.On("New", workDir)}
}

func (_c *ClientFactory_New_Call) Run(run func(workDir string)) *ClientFactory_New_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClientFactory_New_Call) Return(client1 client.Client) *ClientFactory_New_Call {
	_c.Call.Return(client1)
	return _c
}

func (_c *ClientFactory_New_Call) RunAndReturn(run func(workDir string) client.Client) *ClientFactory_New_Call {
	_c.Call.Return(run)
	return _c
}
