// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	events "github.com/JailtonJunior94/ai-spec-harness/internal/runtime/events"
	specs "github.com/JailtonJunior94/ai-spec-harness/internal/runtime/specs"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *Client) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Client_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Client_Expecter) Close() *Client_Close_Call {
	return &Client_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Client_Close_Call) Run(run func()) *Client_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_Close_Call) Return(_a0 error) *Client_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_Close_Call) RunAndReturn(run func() error) *Client_Close_Call {
	_c.Call.Return(run)
	return _c
}

// DroppedUpdates provides a mock function with no fields
func (_m *Client) DroppedUpdates() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DroppedUpdates")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// Client_DroppedUpdates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DroppedUpdates'
type Client_DroppedUpdates_Call struct {
	*mock.Call
}

// DroppedUpdates is a helper method to define mock.On call
func (_e *Client_Expecter) DroppedUpdates() *Client_DroppedUpdates_Call {
	return &Client_DroppedUpdates_Call{Call: _e.mock.On("DroppedUpdates")}
}

func (_c *Client_DroppedUpdates_Call) Run(run func()) *Client_DroppedUpdates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_DroppedUpdates_Call) Return(_a0 uint64) *Client_DroppedUpdates_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_DroppedUpdates_Call) RunAndReturn(run func() uint64) *Client_DroppedUpdates_Call {
	_c.Call.Return(run)
	return _c
}

// Err provides a mock function with no fields
func (_m *Client) Err() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type Client_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *Client_Expecter) Err() *Client_Err_Call {
	return &Client_Err_Call{Call: _e.mock.On("Err")}
}

func (_c *Client_Err_Call) Run(run func()) *Client_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_Err_Call) Return(_a0 error) *Client_Err_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_Err_Call) RunAndReturn(run func() error) *Client_Err_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function with given fields: ctx, launcher, prompt
func (_m *Client) Open(ctx context.Context, launcher specs.Launcher, prompt string) error {
	ret := _m.Called(ctx, launcher, prompt)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, specs.Launcher, string) error); ok {
		r0 = rf(ctx, launcher, prompt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type Client_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - ctx context.Context
//   - launcher specs.Launcher
//   - prompt string
func (_e *Client_Expecter) Open(ctx any, launcher any, prompt any) *Client_Open_Call {
	return &Client_Open_Call{Call: _e.mock.On("Open", ctx, launcher, prompt)}
}

func (_c *Client_Open_Call) Run(run func(ctx context.Context, launcher specs.Launcher, prompt string)) *Client_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(specs.Launcher), args[2].(string))
	})
	return _c
}

func (_c *Client_Open_Call) Return(_a0 error) *Client_Open_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_Open_Call) RunAndReturn(run func(context.Context, specs.Launcher, string) error) *Client_Open_Call {
	_c.Call.Return(run)
	return _c
}

// SlowPublishes provides a mock function with no fields
func (_m *Client) SlowPublishes() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SlowPublishes")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// Client_SlowPublishes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SlowPublishes'
type Client_SlowPublishes_Call struct {
	*mock.Call
}

// SlowPublishes is a helper method to define mock.On call
func (_e *Client_Expecter) SlowPublishes() *Client_SlowPublishes_Call {
	return &Client_SlowPublishes_Call{Call: _e.mock.On("SlowPublishes")}
}

func (_c *Client_SlowPublishes_Call) Run(run func()) *Client_SlowPublishes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_SlowPublishes_Call) Return(_a0 uint64) *Client_SlowPublishes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_SlowPublishes_Call) RunAndReturn(run func() uint64) *Client_SlowPublishes_Call {
	_c.Call.Return(run)
	return _c
}

// Updates provides a mock function with no fields
func (_m *Client) Updates() <-chan events.Event {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Updates")
	}

	var r0 <-chan events.Event
	if rf, ok := ret.Get(0).(func() <-chan events.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan events.Event)
		}
	}

	return r0
}

// Client_Updates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Updates'
type Client_Updates_Call struct {
	*mock.Call
}

// Updates is a helper method to define mock.On call
func (_e *Client_Expecter) Updates() *Client_Updates_Call {
	return &Client_Updates_Call{Call: _e.mock.On("Updates")}
}

func (_c *Client_Updates_Call) Run(run func()) *Client_Updates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Client_Updates_Call) Return(_a0 <-chan events.Event) *Client_Updates_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_Updates_Call) RunAndReturn(run func() <-chan events.Event) *Client_Updates_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
