// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewIOProvider creates a new instance of IOProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIOProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *IOProvider {
	mock := &IOProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// IOProvider is an autogenerated mock type for the IOProvider type
type IOProvider struct {
	mock.Mock
}

type IOProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *IOProvider) EXPECT() *IOProvider_Expecter {
	return &IOProvider_Expecter{mock: &_m.Mock}
}

// Provide provides a mock function for the type IOProvider
func (_mock *IOProvider) Provide() (io.Writer, io.Reader, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Provide")
	}

	var r0 io.Writer
	var r1 io.Reader
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (io.Writer, io.Reader, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() io.Writer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() io.Reader); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(io.Reader)
		}
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// IOProvider_Provide_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Provide'
type IOProvider_Provide_Call struct {
	*mock.Call
}

// Provide is a helper method to define mock.On call
func (_e *IOProvider_Expecter) Provide() *IOProvider_Provide_Call {
	return &IOProvider_Provide_Call{Call: _e.mock.On("Provide")}
}

func (_c *IOProvider_Provide_Call) Run(run func()) *IOProvider_Provide_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IOProvider_Provide_Call) Return(writer io.Writer, reader io.Reader, err error) *IOProvider_Provide_Call {
	_c.Call.Return(writer, reader, err)
	return _c
}

func (_c *IOProvider_Provide_Call) RunAndReturn(run func() (io.Writer, io.Reader, error)) *IOProvider_Provide_Call {
	_c.Call.Return(run)
	return _c
}
